/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Leekwars Tools API
 * OpenAPI spec version: 4.2.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  GetCountByPoolRunIdResponse,
  GetFightsByPoolRunIdResponse,
} from '../leekwarsToolsAPI.schemas';

import { apiClient } from '.././lib/api-client';

/**
 * Retrieves a list of fights associated with a specific pool run ID.
 * @summary Get fights by pool run ID
 */
export const getApiFightDuelGetByPoolRunIdId = (
  id: string,
  signal?: AbortSignal,
) => {
  return apiClient<GetFightsByPoolRunIdResponse>({
    url: `/api/fight/duel/get-by-pool-run-id/${id}`,
    method: 'GET',
    signal,
  });
};

export const getGetApiFightDuelGetByPoolRunIdIdQueryKey = (id: string) => {
  return [`/api/fight/duel/get-by-pool-run-id/${id}`] as const;
};

export const getGetApiFightDuelGetByPoolRunIdIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiFightDuelGetByPoolRunIdId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiFightDuelGetByPoolRunIdId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiFightDuelGetByPoolRunIdIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiFightDuelGetByPoolRunIdId>>
  > = ({ signal }) => getApiFightDuelGetByPoolRunIdId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiFightDuelGetByPoolRunIdId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiFightDuelGetByPoolRunIdIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiFightDuelGetByPoolRunIdId>>
>;
export type GetApiFightDuelGetByPoolRunIdIdQueryError = void;

export function useGetApiFightDuelGetByPoolRunIdId<
  TData = Awaited<ReturnType<typeof getApiFightDuelGetByPoolRunIdId>>,
  TError = void,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiFightDuelGetByPoolRunIdId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiFightDuelGetByPoolRunIdId>>,
          TError,
          Awaited<ReturnType<typeof getApiFightDuelGetByPoolRunIdId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiFightDuelGetByPoolRunIdId<
  TData = Awaited<ReturnType<typeof getApiFightDuelGetByPoolRunIdId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiFightDuelGetByPoolRunIdId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiFightDuelGetByPoolRunIdId>>,
          TError,
          Awaited<ReturnType<typeof getApiFightDuelGetByPoolRunIdId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiFightDuelGetByPoolRunIdId<
  TData = Awaited<ReturnType<typeof getApiFightDuelGetByPoolRunIdId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiFightDuelGetByPoolRunIdId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get fights by pool run ID
 */

export function useGetApiFightDuelGetByPoolRunIdId<
  TData = Awaited<ReturnType<typeof getApiFightDuelGetByPoolRunIdId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiFightDuelGetByPoolRunIdId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiFightDuelGetByPoolRunIdIdQueryOptions(
    id,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Retrieves the count of fights associated with a specific pool run ID.
 * @summary Get fight count by pool run ID
 */
export const getApiFightDuelGetCountByPoolRunIdId = (
  id: string,
  signal?: AbortSignal,
) => {
  return apiClient<GetCountByPoolRunIdResponse>({
    url: `/api/fight/duel/get-count-by-pool-run-id/${id}`,
    method: 'GET',
    signal,
  });
};

export const getGetApiFightDuelGetCountByPoolRunIdIdQueryKey = (id: string) => {
  return [`/api/fight/duel/get-count-by-pool-run-id/${id}`] as const;
};

export const getGetApiFightDuelGetCountByPoolRunIdIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiFightDuelGetCountByPoolRunIdId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiFightDuelGetCountByPoolRunIdId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetApiFightDuelGetCountByPoolRunIdIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiFightDuelGetCountByPoolRunIdId>>
  > = ({ signal }) => getApiFightDuelGetCountByPoolRunIdId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiFightDuelGetCountByPoolRunIdId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiFightDuelGetCountByPoolRunIdIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiFightDuelGetCountByPoolRunIdId>>
>;
export type GetApiFightDuelGetCountByPoolRunIdIdQueryError = void;

export function useGetApiFightDuelGetCountByPoolRunIdId<
  TData = Awaited<ReturnType<typeof getApiFightDuelGetCountByPoolRunIdId>>,
  TError = void,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiFightDuelGetCountByPoolRunIdId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiFightDuelGetCountByPoolRunIdId>>,
          TError,
          Awaited<ReturnType<typeof getApiFightDuelGetCountByPoolRunIdId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiFightDuelGetCountByPoolRunIdId<
  TData = Awaited<ReturnType<typeof getApiFightDuelGetCountByPoolRunIdId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiFightDuelGetCountByPoolRunIdId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiFightDuelGetCountByPoolRunIdId>>,
          TError,
          Awaited<ReturnType<typeof getApiFightDuelGetCountByPoolRunIdId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiFightDuelGetCountByPoolRunIdId<
  TData = Awaited<ReturnType<typeof getApiFightDuelGetCountByPoolRunIdId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiFightDuelGetCountByPoolRunIdId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get fight count by pool run ID
 */

export function useGetApiFightDuelGetCountByPoolRunIdId<
  TData = Awaited<ReturnType<typeof getApiFightDuelGetCountByPoolRunIdId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiFightDuelGetCountByPoolRunIdId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiFightDuelGetCountByPoolRunIdIdQueryOptions(
    id,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
