/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Leekwars Tools API
 * OpenAPI spec version: 4.2.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  GenerateFightRequest,
  GenerateFightResponse,
  GetCountByPoolRunIdResponse,
  GetDuelFightsByPoolRunIdResponse,
  PoolFightRatioListResponse,
  PoolFightRatioResponse,
} from '../leekwarsToolsAPI.schemas';

import { apiClient } from '.././lib/api-client';

/**
 * Generates a fight based on the provided fight ID. The fight ID should correspond to an existing fight in the system.
 * @summary Generate a fight
 */
export const postFightDuelGenerate = (
  generateFightRequest: GenerateFightRequest,
  signal?: AbortSignal,
) => {
  return apiClient<GenerateFightResponse>({
    url: `/fight/duel/generate`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: generateFightRequest,
    signal,
  });
};

export const getPostFightDuelGenerateMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postFightDuelGenerate>>,
    TError,
    { data: GenerateFightRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postFightDuelGenerate>>,
  TError,
  { data: GenerateFightRequest },
  TContext
> => {
  const mutationKey = ['postFightDuelGenerate'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postFightDuelGenerate>>,
    { data: GenerateFightRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postFightDuelGenerate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostFightDuelGenerateMutationResult = NonNullable<
  Awaited<ReturnType<typeof postFightDuelGenerate>>
>;
export type PostFightDuelGenerateMutationBody = GenerateFightRequest;
export type PostFightDuelGenerateMutationError = void;

/**
 * @summary Generate a fight
 */
export const usePostFightDuelGenerate = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postFightDuelGenerate>>,
      TError,
      { data: GenerateFightRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postFightDuelGenerate>>,
  TError,
  { data: GenerateFightRequest },
  TContext
> => {
  return useMutation(
    getPostFightDuelGenerateMutationOptions(options),
    queryClient,
  );
};
/**
 * Retrieves a list of fights associated with a specific pool run ID.
 * @summary Get fights by pool run ID
 */
export const getFightDuelGetByPoolRunIdIdOffsetLimit = (
  id: string,
  offset: string,
  limit: string,
  signal?: AbortSignal,
) => {
  return apiClient<GetDuelFightsByPoolRunIdResponse>({
    url: `/fight/duel/get-by-pool-run-id/${id}/${offset}/${limit}`,
    method: 'GET',
    signal,
  });
};

export const getGetFightDuelGetByPoolRunIdIdOffsetLimitQueryKey = (
  id: string,
  offset: string,
  limit: string,
) => {
  return [`/fight/duel/get-by-pool-run-id/${id}/${offset}/${limit}`] as const;
};

export const getGetFightDuelGetByPoolRunIdIdOffsetLimitQueryOptions = <
  TData = Awaited<ReturnType<typeof getFightDuelGetByPoolRunIdIdOffsetLimit>>,
  TError = void,
>(
  id: string,
  offset: string,
  limit: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightDuelGetByPoolRunIdIdOffsetLimit>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetFightDuelGetByPoolRunIdIdOffsetLimitQueryKey(id, offset, limit);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getFightDuelGetByPoolRunIdIdOffsetLimit>>
  > = ({ signal }) =>
    getFightDuelGetByPoolRunIdIdOffsetLimit(id, offset, limit, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(id && offset && limit),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getFightDuelGetByPoolRunIdIdOffsetLimit>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetFightDuelGetByPoolRunIdIdOffsetLimitQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFightDuelGetByPoolRunIdIdOffsetLimit>>
>;
export type GetFightDuelGetByPoolRunIdIdOffsetLimitQueryError = void;

export function useGetFightDuelGetByPoolRunIdIdOffsetLimit<
  TData = Awaited<ReturnType<typeof getFightDuelGetByPoolRunIdIdOffsetLimit>>,
  TError = void,
>(
  id: string,
  offset: string,
  limit: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightDuelGetByPoolRunIdIdOffsetLimit>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFightDuelGetByPoolRunIdIdOffsetLimit>>,
          TError,
          Awaited<ReturnType<typeof getFightDuelGetByPoolRunIdIdOffsetLimit>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFightDuelGetByPoolRunIdIdOffsetLimit<
  TData = Awaited<ReturnType<typeof getFightDuelGetByPoolRunIdIdOffsetLimit>>,
  TError = void,
>(
  id: string,
  offset: string,
  limit: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightDuelGetByPoolRunIdIdOffsetLimit>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFightDuelGetByPoolRunIdIdOffsetLimit>>,
          TError,
          Awaited<ReturnType<typeof getFightDuelGetByPoolRunIdIdOffsetLimit>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFightDuelGetByPoolRunIdIdOffsetLimit<
  TData = Awaited<ReturnType<typeof getFightDuelGetByPoolRunIdIdOffsetLimit>>,
  TError = void,
>(
  id: string,
  offset: string,
  limit: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightDuelGetByPoolRunIdIdOffsetLimit>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get fights by pool run ID
 */

export function useGetFightDuelGetByPoolRunIdIdOffsetLimit<
  TData = Awaited<ReturnType<typeof getFightDuelGetByPoolRunIdIdOffsetLimit>>,
  TError = void,
>(
  id: string,
  offset: string,
  limit: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightDuelGetByPoolRunIdIdOffsetLimit>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetFightDuelGetByPoolRunIdIdOffsetLimitQueryOptions(
    id,
    offset,
    limit,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Retrieves the count of fights associated with a specific pool run ID.
 * @summary Get fight count by pool run ID
 */
export const getFightDuelGetCountByPoolRunIdId = (
  id: string,
  signal?: AbortSignal,
) => {
  return apiClient<GetCountByPoolRunIdResponse>({
    url: `/fight/duel/get-count-by-pool-run-id/${id}`,
    method: 'GET',
    signal,
  });
};

export const getGetFightDuelGetCountByPoolRunIdIdQueryKey = (id: string) => {
  return [`/fight/duel/get-count-by-pool-run-id/${id}`] as const;
};

export const getGetFightDuelGetCountByPoolRunIdIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getFightDuelGetCountByPoolRunIdId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightDuelGetCountByPoolRunIdId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetFightDuelGetCountByPoolRunIdIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getFightDuelGetCountByPoolRunIdId>>
  > = ({ signal }) => getFightDuelGetCountByPoolRunIdId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getFightDuelGetCountByPoolRunIdId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetFightDuelGetCountByPoolRunIdIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFightDuelGetCountByPoolRunIdId>>
>;
export type GetFightDuelGetCountByPoolRunIdIdQueryError = void;

export function useGetFightDuelGetCountByPoolRunIdId<
  TData = Awaited<ReturnType<typeof getFightDuelGetCountByPoolRunIdId>>,
  TError = void,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightDuelGetCountByPoolRunIdId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFightDuelGetCountByPoolRunIdId>>,
          TError,
          Awaited<ReturnType<typeof getFightDuelGetCountByPoolRunIdId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFightDuelGetCountByPoolRunIdId<
  TData = Awaited<ReturnType<typeof getFightDuelGetCountByPoolRunIdId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightDuelGetCountByPoolRunIdId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFightDuelGetCountByPoolRunIdId>>,
          TError,
          Awaited<ReturnType<typeof getFightDuelGetCountByPoolRunIdId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFightDuelGetCountByPoolRunIdId<
  TData = Awaited<ReturnType<typeof getFightDuelGetCountByPoolRunIdId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightDuelGetCountByPoolRunIdId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get fight count by pool run ID
 */

export function useGetFightDuelGetCountByPoolRunIdId<
  TData = Awaited<ReturnType<typeof getFightDuelGetCountByPoolRunIdId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightDuelGetCountByPoolRunIdId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetFightDuelGetCountByPoolRunIdIdQueryOptions(
    id,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Retrieves the fight ratios for all leeks in a specific pool run.
 * @summary Get all leek ratios by pool run ID
 */
export const getFightDuelLeekRatioPoolRunIdAll = (
  poolRunId: string,
  signal?: AbortSignal,
) => {
  return apiClient<PoolFightRatioListResponse>({
    url: `/fight/duel/leek-ratio/${poolRunId}/all`,
    method: 'GET',
    signal,
  });
};

export const getGetFightDuelLeekRatioPoolRunIdAllQueryKey = (
  poolRunId: string,
) => {
  return [`/fight/duel/leek-ratio/${poolRunId}/all`] as const;
};

export const getGetFightDuelLeekRatioPoolRunIdAllQueryOptions = <
  TData = Awaited<ReturnType<typeof getFightDuelLeekRatioPoolRunIdAll>>,
  TError = void,
>(
  poolRunId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightDuelLeekRatioPoolRunIdAll>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetFightDuelLeekRatioPoolRunIdAllQueryKey(poolRunId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getFightDuelLeekRatioPoolRunIdAll>>
  > = ({ signal }) => getFightDuelLeekRatioPoolRunIdAll(poolRunId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!poolRunId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getFightDuelLeekRatioPoolRunIdAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetFightDuelLeekRatioPoolRunIdAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFightDuelLeekRatioPoolRunIdAll>>
>;
export type GetFightDuelLeekRatioPoolRunIdAllQueryError = void;

export function useGetFightDuelLeekRatioPoolRunIdAll<
  TData = Awaited<ReturnType<typeof getFightDuelLeekRatioPoolRunIdAll>>,
  TError = void,
>(
  poolRunId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightDuelLeekRatioPoolRunIdAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFightDuelLeekRatioPoolRunIdAll>>,
          TError,
          Awaited<ReturnType<typeof getFightDuelLeekRatioPoolRunIdAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFightDuelLeekRatioPoolRunIdAll<
  TData = Awaited<ReturnType<typeof getFightDuelLeekRatioPoolRunIdAll>>,
  TError = void,
>(
  poolRunId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightDuelLeekRatioPoolRunIdAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFightDuelLeekRatioPoolRunIdAll>>,
          TError,
          Awaited<ReturnType<typeof getFightDuelLeekRatioPoolRunIdAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFightDuelLeekRatioPoolRunIdAll<
  TData = Awaited<ReturnType<typeof getFightDuelLeekRatioPoolRunIdAll>>,
  TError = void,
>(
  poolRunId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightDuelLeekRatioPoolRunIdAll>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all leek ratios by pool run ID
 */

export function useGetFightDuelLeekRatioPoolRunIdAll<
  TData = Awaited<ReturnType<typeof getFightDuelLeekRatioPoolRunIdAll>>,
  TError = void,
>(
  poolRunId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightDuelLeekRatioPoolRunIdAll>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetFightDuelLeekRatioPoolRunIdAllQueryOptions(
    poolRunId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Retrieves the fight ratio for a specific leek in a specific pool run.
 * @summary Get leek ratio by pool run ID and leek ID
 */
export const getFightDuelLeekRatioPoolRunIdLeekId = (
  poolRunId: string,
  leekId: string,
  signal?: AbortSignal,
) => {
  return apiClient<PoolFightRatioResponse>({
    url: `/fight/duel/leek-ratio/${poolRunId}/${leekId}`,
    method: 'GET',
    signal,
  });
};

export const getGetFightDuelLeekRatioPoolRunIdLeekIdQueryKey = (
  poolRunId: string,
  leekId: string,
) => {
  return [`/fight/duel/leek-ratio/${poolRunId}/${leekId}`] as const;
};

export const getGetFightDuelLeekRatioPoolRunIdLeekIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getFightDuelLeekRatioPoolRunIdLeekId>>,
  TError = void,
>(
  poolRunId: string,
  leekId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightDuelLeekRatioPoolRunIdLeekId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetFightDuelLeekRatioPoolRunIdLeekIdQueryKey(poolRunId, leekId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getFightDuelLeekRatioPoolRunIdLeekId>>
  > = ({ signal }) =>
    getFightDuelLeekRatioPoolRunIdLeekId(poolRunId, leekId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(poolRunId && leekId),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getFightDuelLeekRatioPoolRunIdLeekId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetFightDuelLeekRatioPoolRunIdLeekIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFightDuelLeekRatioPoolRunIdLeekId>>
>;
export type GetFightDuelLeekRatioPoolRunIdLeekIdQueryError = void;

export function useGetFightDuelLeekRatioPoolRunIdLeekId<
  TData = Awaited<ReturnType<typeof getFightDuelLeekRatioPoolRunIdLeekId>>,
  TError = void,
>(
  poolRunId: string,
  leekId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightDuelLeekRatioPoolRunIdLeekId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFightDuelLeekRatioPoolRunIdLeekId>>,
          TError,
          Awaited<ReturnType<typeof getFightDuelLeekRatioPoolRunIdLeekId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFightDuelLeekRatioPoolRunIdLeekId<
  TData = Awaited<ReturnType<typeof getFightDuelLeekRatioPoolRunIdLeekId>>,
  TError = void,
>(
  poolRunId: string,
  leekId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightDuelLeekRatioPoolRunIdLeekId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFightDuelLeekRatioPoolRunIdLeekId>>,
          TError,
          Awaited<ReturnType<typeof getFightDuelLeekRatioPoolRunIdLeekId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFightDuelLeekRatioPoolRunIdLeekId<
  TData = Awaited<ReturnType<typeof getFightDuelLeekRatioPoolRunIdLeekId>>,
  TError = void,
>(
  poolRunId: string,
  leekId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightDuelLeekRatioPoolRunIdLeekId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get leek ratio by pool run ID and leek ID
 */

export function useGetFightDuelLeekRatioPoolRunIdLeekId<
  TData = Awaited<ReturnType<typeof getFightDuelLeekRatioPoolRunIdLeekId>>,
  TError = void,
>(
  poolRunId: string,
  leekId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightDuelLeekRatioPoolRunIdLeekId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetFightDuelLeekRatioPoolRunIdLeekIdQueryOptions(
    poolRunId,
    leekId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
