/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Leekwars Tools API
 * OpenAPI spec version: 4.2.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { GetAllRunningPoolsResponse } from '../leekwarsToolsAPI.schemas';

import { apiClient } from '.././lib/api-client';

/**
 * @summary Get all running pool runs
 */
export const getAllRunningPools = (signal?: AbortSignal) => {
  return apiClient<GetAllRunningPoolsResponse>({
    url: `/all-running-pools`,
    method: 'GET',
    signal,
  });
};

export const getGetAllRunningPoolsQueryKey = () => {
  return [`/all-running-pools`] as const;
};

export const getGetAllRunningPoolsQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllRunningPools>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getAllRunningPools>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAllRunningPoolsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAllRunningPools>>
  > = ({ signal }) => getAllRunningPools(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllRunningPools>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAllRunningPoolsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllRunningPools>>
>;
export type GetAllRunningPoolsQueryError = void;

export function useGetAllRunningPools<
  TData = Awaited<ReturnType<typeof getAllRunningPools>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllRunningPools>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllRunningPools>>,
          TError,
          Awaited<ReturnType<typeof getAllRunningPools>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAllRunningPools<
  TData = Awaited<ReturnType<typeof getAllRunningPools>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllRunningPools>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllRunningPools>>,
          TError,
          Awaited<ReturnType<typeof getAllRunningPools>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAllRunningPools<
  TData = Awaited<ReturnType<typeof getAllRunningPools>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllRunningPools>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all running pool runs
 */

export function useGetAllRunningPools<
  TData = Awaited<ReturnType<typeof getAllRunningPools>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllRunningPools>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAllRunningPoolsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
