/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Leekwars Tools API
 * OpenAPI spec version: 4.2.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  BasePoolStopResponse,
  DuelPoolRunResponse,
  ListDuelPoolRunResponse,
} from '../leekwarsToolsAPI.schemas';

import { apiClient } from '.././lib/api-client';

/**
 * Retrieves all duel pool runs, including the leeks in each pool and their current Elo ratings.
 * @summary Get all duel pool runs
 */
export const getDuelPoolRunAll = (signal?: AbortSignal) => {
  return apiClient<ListDuelPoolRunResponse>({
    url: `/duel-pool-run/all`,
    method: 'GET',
    signal,
  });
};

export const getGetDuelPoolRunAllQueryKey = () => {
  return [`/duel-pool-run/all`] as const;
};

export const getGetDuelPoolRunAllQueryOptions = <
  TData = Awaited<ReturnType<typeof getDuelPoolRunAll>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getDuelPoolRunAll>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDuelPoolRunAllQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getDuelPoolRunAll>>
  > = ({ signal }) => getDuelPoolRunAll(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDuelPoolRunAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDuelPoolRunAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDuelPoolRunAll>>
>;
export type GetDuelPoolRunAllQueryError = void;

export function useGetDuelPoolRunAll<
  TData = Awaited<ReturnType<typeof getDuelPoolRunAll>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDuelPoolRunAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDuelPoolRunAll>>,
          TError,
          Awaited<ReturnType<typeof getDuelPoolRunAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDuelPoolRunAll<
  TData = Awaited<ReturnType<typeof getDuelPoolRunAll>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDuelPoolRunAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDuelPoolRunAll>>,
          TError,
          Awaited<ReturnType<typeof getDuelPoolRunAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDuelPoolRunAll<
  TData = Awaited<ReturnType<typeof getDuelPoolRunAll>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDuelPoolRunAll>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all duel pool runs
 */

export function useGetDuelPoolRunAll<
  TData = Awaited<ReturnType<typeof getDuelPoolRunAll>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDuelPoolRunAll>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetDuelPoolRunAllQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Retrieves all duel pool runs associated with a specific duel pool ID, including the leeks in each pool and their current Elo ratings.
 * @summary Get duel pool runs by duel pool ID
 */
export const getDuelPoolRunGetByPoolIdId = (
  id: string,
  signal?: AbortSignal,
) => {
  return apiClient<ListDuelPoolRunResponse>({
    url: `/duel-pool-run/get-by-pool-id/${id}`,
    method: 'GET',
    signal,
  });
};

export const getGetDuelPoolRunGetByPoolIdIdQueryKey = (id: string) => {
  return [`/duel-pool-run/get-by-pool-id/${id}`] as const;
};

export const getGetDuelPoolRunGetByPoolIdIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getDuelPoolRunGetByPoolIdId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDuelPoolRunGetByPoolIdId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetDuelPoolRunGetByPoolIdIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getDuelPoolRunGetByPoolIdId>>
  > = ({ signal }) => getDuelPoolRunGetByPoolIdId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getDuelPoolRunGetByPoolIdId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDuelPoolRunGetByPoolIdIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDuelPoolRunGetByPoolIdId>>
>;
export type GetDuelPoolRunGetByPoolIdIdQueryError = void;

export function useGetDuelPoolRunGetByPoolIdId<
  TData = Awaited<ReturnType<typeof getDuelPoolRunGetByPoolIdId>>,
  TError = void,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDuelPoolRunGetByPoolIdId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDuelPoolRunGetByPoolIdId>>,
          TError,
          Awaited<ReturnType<typeof getDuelPoolRunGetByPoolIdId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDuelPoolRunGetByPoolIdId<
  TData = Awaited<ReturnType<typeof getDuelPoolRunGetByPoolIdId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDuelPoolRunGetByPoolIdId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDuelPoolRunGetByPoolIdId>>,
          TError,
          Awaited<ReturnType<typeof getDuelPoolRunGetByPoolIdId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDuelPoolRunGetByPoolIdId<
  TData = Awaited<ReturnType<typeof getDuelPoolRunGetByPoolIdId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDuelPoolRunGetByPoolIdId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get duel pool runs by duel pool ID
 */

export function useGetDuelPoolRunGetByPoolIdId<
  TData = Awaited<ReturnType<typeof getDuelPoolRunGetByPoolIdId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDuelPoolRunGetByPoolIdId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetDuelPoolRunGetByPoolIdIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Retrieves a duel pool run by its ID, including the leeks in the pool and their current Elo ratings.
 * @summary Get duel pool run by ID
 */
export const getDuelPoolRunId = (id: string, signal?: AbortSignal) => {
  return apiClient<DuelPoolRunResponse>({
    url: `/duel-pool-run/${id}`,
    method: 'GET',
    signal,
  });
};

export const getGetDuelPoolRunIdQueryKey = (id: string) => {
  return [`/duel-pool-run/${id}`] as const;
};

export const getGetDuelPoolRunIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getDuelPoolRunId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDuelPoolRunId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDuelPoolRunIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getDuelPoolRunId>>
  > = ({ signal }) => getDuelPoolRunId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getDuelPoolRunId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDuelPoolRunIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDuelPoolRunId>>
>;
export type GetDuelPoolRunIdQueryError = void;

export function useGetDuelPoolRunId<
  TData = Awaited<ReturnType<typeof getDuelPoolRunId>>,
  TError = void,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDuelPoolRunId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDuelPoolRunId>>,
          TError,
          Awaited<ReturnType<typeof getDuelPoolRunId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDuelPoolRunId<
  TData = Awaited<ReturnType<typeof getDuelPoolRunId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDuelPoolRunId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDuelPoolRunId>>,
          TError,
          Awaited<ReturnType<typeof getDuelPoolRunId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDuelPoolRunId<
  TData = Awaited<ReturnType<typeof getDuelPoolRunId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDuelPoolRunId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get duel pool run by ID
 */

export function useGetDuelPoolRunId<
  TData = Awaited<ReturnType<typeof getDuelPoolRunId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDuelPoolRunId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetDuelPoolRunIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Starts a duel pool run, which will generate fights based on the leeks in the pool and the pool's configuration.
 * @summary Start a duel pool run
 */
export const postDuelPoolRunIdStart = (id: string, signal?: AbortSignal) => {
  return apiClient<DuelPoolRunResponse>({
    url: `/duel-pool-run/${id}/start`,
    method: 'POST',
    signal,
  });
};

export const getPostDuelPoolRunIdStartMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postDuelPoolRunIdStart>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postDuelPoolRunIdStart>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['postDuelPoolRunIdStart'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postDuelPoolRunIdStart>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return postDuelPoolRunIdStart(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostDuelPoolRunIdStartMutationResult = NonNullable<
  Awaited<ReturnType<typeof postDuelPoolRunIdStart>>
>;

export type PostDuelPoolRunIdStartMutationError = void;

/**
 * @summary Start a duel pool run
 */
export const usePostDuelPoolRunIdStart = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postDuelPoolRunIdStart>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postDuelPoolRunIdStart>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getPostDuelPoolRunIdStartMutationOptions(options),
    queryClient,
  );
};
/**
 * Stops a duel pool run, which will stop all ongoing fights and prevent new fights from being generated.
 * @summary Stop a duel pool run
 */
export const postDuelPoolRunIdStop = (id: string, signal?: AbortSignal) => {
  return apiClient<BasePoolStopResponse>({
    url: `/duel-pool-run/${id}/stop`,
    method: 'POST',
    signal,
  });
};

export const getPostDuelPoolRunIdStopMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postDuelPoolRunIdStop>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postDuelPoolRunIdStop>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['postDuelPoolRunIdStop'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postDuelPoolRunIdStop>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return postDuelPoolRunIdStop(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostDuelPoolRunIdStopMutationResult = NonNullable<
  Awaited<ReturnType<typeof postDuelPoolRunIdStop>>
>;

export type PostDuelPoolRunIdStopMutationError = void;

/**
 * @summary Stop a duel pool run
 */
export const usePostDuelPoolRunIdStop = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postDuelPoolRunIdStop>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postDuelPoolRunIdStop>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getPostDuelPoolRunIdStopMutationOptions(options),
    queryClient,
  );
};
