/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Leekwars Tools API
 * OpenAPI spec version: 4.2.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  DuelPoolRunResponse,
  ListDuelPoolRunResponse,
} from '../leekwarsToolsAPI.schemas';

import { apiClient } from '.././lib/api-client';

/**
 * Retrieves all duel pool runs, including the leeks in each pool and their current Elo ratings.
 * @summary Get all duel pool runs
 */
export const getDuelPoolRunsAll = (signal?: AbortSignal) => {
  return apiClient<ListDuelPoolRunResponse>({
    url: `/duel-pool-runs/all`,
    method: 'GET',
    signal,
  });
};

export const getGetDuelPoolRunsAllQueryKey = () => {
  return [`/duel-pool-runs/all`] as const;
};

export const getGetDuelPoolRunsAllQueryOptions = <
  TData = Awaited<ReturnType<typeof getDuelPoolRunsAll>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getDuelPoolRunsAll>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDuelPoolRunsAllQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getDuelPoolRunsAll>>
  > = ({ signal }) => getDuelPoolRunsAll(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDuelPoolRunsAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDuelPoolRunsAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDuelPoolRunsAll>>
>;
export type GetDuelPoolRunsAllQueryError = void;

export function useGetDuelPoolRunsAll<
  TData = Awaited<ReturnType<typeof getDuelPoolRunsAll>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDuelPoolRunsAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDuelPoolRunsAll>>,
          TError,
          Awaited<ReturnType<typeof getDuelPoolRunsAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDuelPoolRunsAll<
  TData = Awaited<ReturnType<typeof getDuelPoolRunsAll>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDuelPoolRunsAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDuelPoolRunsAll>>,
          TError,
          Awaited<ReturnType<typeof getDuelPoolRunsAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDuelPoolRunsAll<
  TData = Awaited<ReturnType<typeof getDuelPoolRunsAll>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDuelPoolRunsAll>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all duel pool runs
 */

export function useGetDuelPoolRunsAll<
  TData = Awaited<ReturnType<typeof getDuelPoolRunsAll>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDuelPoolRunsAll>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetDuelPoolRunsAllQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Retrieves a duel pool run by its ID, including the leeks in the pool and their current Elo ratings.
 * @summary Get duel pool run by ID
 */
export const getDuelPoolRunsId = (id: string, signal?: AbortSignal) => {
  return apiClient<DuelPoolRunResponse>({
    url: `/duel-pool-runs/${id}`,
    method: 'GET',
    signal,
  });
};

export const getGetDuelPoolRunsIdQueryKey = (id: string) => {
  return [`/duel-pool-runs/${id}`] as const;
};

export const getGetDuelPoolRunsIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getDuelPoolRunsId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDuelPoolRunsId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDuelPoolRunsIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getDuelPoolRunsId>>
  > = ({ signal }) => getDuelPoolRunsId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getDuelPoolRunsId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDuelPoolRunsIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDuelPoolRunsId>>
>;
export type GetDuelPoolRunsIdQueryError = void;

export function useGetDuelPoolRunsId<
  TData = Awaited<ReturnType<typeof getDuelPoolRunsId>>,
  TError = void,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDuelPoolRunsId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDuelPoolRunsId>>,
          TError,
          Awaited<ReturnType<typeof getDuelPoolRunsId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDuelPoolRunsId<
  TData = Awaited<ReturnType<typeof getDuelPoolRunsId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDuelPoolRunsId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDuelPoolRunsId>>,
          TError,
          Awaited<ReturnType<typeof getDuelPoolRunsId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDuelPoolRunsId<
  TData = Awaited<ReturnType<typeof getDuelPoolRunsId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDuelPoolRunsId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get duel pool run by ID
 */

export function useGetDuelPoolRunsId<
  TData = Awaited<ReturnType<typeof getDuelPoolRunsId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDuelPoolRunsId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetDuelPoolRunsIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Starts a duel pool run, which will generate fights based on the leeks in the pool and the pool's configuration.
 * @summary Start a duel pool run
 */
export const postDuelPoolRunsIdStart = (id: string, signal?: AbortSignal) => {
  return apiClient<DuelPoolRunResponse>({
    url: `/duel-pool-runs/${id}/start`,
    method: 'POST',
    signal,
  });
};

export const getPostDuelPoolRunsIdStartMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postDuelPoolRunsIdStart>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postDuelPoolRunsIdStart>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['postDuelPoolRunsIdStart'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postDuelPoolRunsIdStart>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return postDuelPoolRunsIdStart(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostDuelPoolRunsIdStartMutationResult = NonNullable<
  Awaited<ReturnType<typeof postDuelPoolRunsIdStart>>
>;

export type PostDuelPoolRunsIdStartMutationError = void;

/**
 * @summary Start a duel pool run
 */
export const usePostDuelPoolRunsIdStart = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postDuelPoolRunsIdStart>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postDuelPoolRunsIdStart>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getPostDuelPoolRunsIdStartMutationOptions(options),
    queryClient,
  );
};
