/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Leekwars Tools API
 * OpenAPI spec version: 4.2.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  CreateFarmerPoolRequest,
  FarmerPoolResponse,
  GetAllFarmerPoolsResponse,
} from '../leekwarsToolsAPI.schemas';

import { apiClient } from '.././lib/api-client';

/**
 * Returns a list of all farmer pools.
 * @summary Get all farmer pools
 */
export const getFarmerPoolsAll = (signal?: AbortSignal) => {
  return apiClient<GetAllFarmerPoolsResponse>({
    url: `/farmer-pools/all`,
    method: 'GET',
    signal,
  });
};

export const getGetFarmerPoolsAllQueryKey = () => {
  return [`/farmer-pools/all`] as const;
};

export const getGetFarmerPoolsAllQueryOptions = <
  TData = Awaited<ReturnType<typeof getFarmerPoolsAll>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getFarmerPoolsAll>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetFarmerPoolsAllQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getFarmerPoolsAll>>
  > = ({ signal }) => getFarmerPoolsAll(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getFarmerPoolsAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetFarmerPoolsAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFarmerPoolsAll>>
>;
export type GetFarmerPoolsAllQueryError = void;

export function useGetFarmerPoolsAll<
  TData = Awaited<ReturnType<typeof getFarmerPoolsAll>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFarmerPoolsAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFarmerPoolsAll>>,
          TError,
          Awaited<ReturnType<typeof getFarmerPoolsAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFarmerPoolsAll<
  TData = Awaited<ReturnType<typeof getFarmerPoolsAll>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFarmerPoolsAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFarmerPoolsAll>>,
          TError,
          Awaited<ReturnType<typeof getFarmerPoolsAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFarmerPoolsAll<
  TData = Awaited<ReturnType<typeof getFarmerPoolsAll>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFarmerPoolsAll>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all farmer pools
 */

export function useGetFarmerPoolsAll<
  TData = Awaited<ReturnType<typeof getFarmerPoolsAll>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFarmerPoolsAll>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetFarmerPoolsAllQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Creates a new farmer pool.
 * @summary Create a farmer pool
 */
export const postFarmerPoolsCreate = (
  createFarmerPoolRequest: CreateFarmerPoolRequest,
  signal?: AbortSignal,
) => {
  return apiClient<FarmerPoolResponse>({
    url: `/farmer-pools/create`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createFarmerPoolRequest,
    signal,
  });
};

export const getPostFarmerPoolsCreateMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postFarmerPoolsCreate>>,
    TError,
    { data: CreateFarmerPoolRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postFarmerPoolsCreate>>,
  TError,
  { data: CreateFarmerPoolRequest },
  TContext
> => {
  const mutationKey = ['postFarmerPoolsCreate'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postFarmerPoolsCreate>>,
    { data: CreateFarmerPoolRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postFarmerPoolsCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostFarmerPoolsCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof postFarmerPoolsCreate>>
>;
export type PostFarmerPoolsCreateMutationBody = CreateFarmerPoolRequest;
export type PostFarmerPoolsCreateMutationError = void;

/**
 * @summary Create a farmer pool
 */
export const usePostFarmerPoolsCreate = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postFarmerPoolsCreate>>,
      TError,
      { data: CreateFarmerPoolRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postFarmerPoolsCreate>>,
  TError,
  { data: CreateFarmerPoolRequest },
  TContext
> => {
  return useMutation(
    getPostFarmerPoolsCreateMutationOptions(options),
    queryClient,
  );
};
/**
 * Returns a farmer pool by its ID.
 * @summary Get a farmer pool by ID
 */
export const getFarmerPoolsId = (id: string, signal?: AbortSignal) => {
  return apiClient<FarmerPoolResponse>({
    url: `/farmer-pools/${id}`,
    method: 'GET',
    signal,
  });
};

export const getGetFarmerPoolsIdQueryKey = (id: string) => {
  return [`/farmer-pools/${id}`] as const;
};

export const getGetFarmerPoolsIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getFarmerPoolsId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFarmerPoolsId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetFarmerPoolsIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getFarmerPoolsId>>
  > = ({ signal }) => getFarmerPoolsId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getFarmerPoolsId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetFarmerPoolsIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFarmerPoolsId>>
>;
export type GetFarmerPoolsIdQueryError = void;

export function useGetFarmerPoolsId<
  TData = Awaited<ReturnType<typeof getFarmerPoolsId>>,
  TError = void,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFarmerPoolsId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFarmerPoolsId>>,
          TError,
          Awaited<ReturnType<typeof getFarmerPoolsId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFarmerPoolsId<
  TData = Awaited<ReturnType<typeof getFarmerPoolsId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFarmerPoolsId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFarmerPoolsId>>,
          TError,
          Awaited<ReturnType<typeof getFarmerPoolsId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFarmerPoolsId<
  TData = Awaited<ReturnType<typeof getFarmerPoolsId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFarmerPoolsId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a farmer pool by ID
 */

export function useGetFarmerPoolsId<
  TData = Awaited<ReturnType<typeof getFarmerPoolsId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFarmerPoolsId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetFarmerPoolsIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
