/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Leekwars Tools API
 * OpenAPI spec version: 4.2.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import type { TeamPoolRunResponse } from '../leekwarsToolsAPI.schemas';

import { apiClient } from '.././lib/api-client';

/**
 * Starts a team pool run, which will generate fights based on the teams in the pool and the pool's configuration.
 * @summary Start a team pool run
 */
export const postTeamPoolRunIdStart = (id: string, signal?: AbortSignal) => {
  return apiClient<TeamPoolRunResponse>({
    url: `/team-pool-run/${id}/start`,
    method: 'POST',
    signal,
  });
};

export const getPostTeamPoolRunIdStartMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postTeamPoolRunIdStart>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postTeamPoolRunIdStart>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['postTeamPoolRunIdStart'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postTeamPoolRunIdStart>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return postTeamPoolRunIdStart(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostTeamPoolRunIdStartMutationResult = NonNullable<
  Awaited<ReturnType<typeof postTeamPoolRunIdStart>>
>;

export type PostTeamPoolRunIdStartMutationError = void;

/**
 * @summary Start a team pool run
 */
export const usePostTeamPoolRunIdStart = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postTeamPoolRunIdStart>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postTeamPoolRunIdStart>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getPostTeamPoolRunIdStartMutationOptions(options),
    queryClient,
  );
};
