/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Leekwars Tools API
 * OpenAPI spec version: 4.2.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  GenerateFightRequest,
  GenerateFightResponse,
  GetCountByPoolRunIdResponse,
  GetTeamFightsByPoolRunIdResponse,
} from '../leekwarsToolsAPI.schemas';

import { apiClient } from '.././lib/api-client';

/**
 * Generates a fight based on the provided fight ID. The fight ID should correspond to an existing fight in the system.
 * @summary Generate a fight
 */
export const postFightTeamGenerate = (
  generateFightRequest: GenerateFightRequest,
  signal?: AbortSignal,
) => {
  return apiClient<GenerateFightResponse>({
    url: `/fight/team/generate`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: generateFightRequest,
    signal,
  });
};

export const getPostFightTeamGenerateMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postFightTeamGenerate>>,
    TError,
    { data: GenerateFightRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postFightTeamGenerate>>,
  TError,
  { data: GenerateFightRequest },
  TContext
> => {
  const mutationKey = ['postFightTeamGenerate'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postFightTeamGenerate>>,
    { data: GenerateFightRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postFightTeamGenerate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostFightTeamGenerateMutationResult = NonNullable<
  Awaited<ReturnType<typeof postFightTeamGenerate>>
>;
export type PostFightTeamGenerateMutationBody = GenerateFightRequest;
export type PostFightTeamGenerateMutationError = void;

/**
 * @summary Generate a fight
 */
export const usePostFightTeamGenerate = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postFightTeamGenerate>>,
      TError,
      { data: GenerateFightRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postFightTeamGenerate>>,
  TError,
  { data: GenerateFightRequest },
  TContext
> => {
  return useMutation(
    getPostFightTeamGenerateMutationOptions(options),
    queryClient,
  );
};
/**
 * Retrieves a list of fights associated with a specific pool run ID.
 * @summary Get fights by pool run ID
 */
export const getFightTeamGetByPoolRunIdIdOffsetLimit = (
  id: string,
  offset: string,
  limit: string,
  signal?: AbortSignal,
) => {
  return apiClient<GetTeamFightsByPoolRunIdResponse>({
    url: `/fight/team/get-by-pool-run-id/${id}/${offset}/${limit}`,
    method: 'GET',
    signal,
  });
};

export const getGetFightTeamGetByPoolRunIdIdOffsetLimitQueryKey = (
  id: string,
  offset: string,
  limit: string,
) => {
  return [`/fight/team/get-by-pool-run-id/${id}/${offset}/${limit}`] as const;
};

export const getGetFightTeamGetByPoolRunIdIdOffsetLimitQueryOptions = <
  TData = Awaited<ReturnType<typeof getFightTeamGetByPoolRunIdIdOffsetLimit>>,
  TError = void,
>(
  id: string,
  offset: string,
  limit: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightTeamGetByPoolRunIdIdOffsetLimit>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetFightTeamGetByPoolRunIdIdOffsetLimitQueryKey(id, offset, limit);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getFightTeamGetByPoolRunIdIdOffsetLimit>>
  > = ({ signal }) =>
    getFightTeamGetByPoolRunIdIdOffsetLimit(id, offset, limit, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(id && offset && limit),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getFightTeamGetByPoolRunIdIdOffsetLimit>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetFightTeamGetByPoolRunIdIdOffsetLimitQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFightTeamGetByPoolRunIdIdOffsetLimit>>
>;
export type GetFightTeamGetByPoolRunIdIdOffsetLimitQueryError = void;

export function useGetFightTeamGetByPoolRunIdIdOffsetLimit<
  TData = Awaited<ReturnType<typeof getFightTeamGetByPoolRunIdIdOffsetLimit>>,
  TError = void,
>(
  id: string,
  offset: string,
  limit: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightTeamGetByPoolRunIdIdOffsetLimit>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFightTeamGetByPoolRunIdIdOffsetLimit>>,
          TError,
          Awaited<ReturnType<typeof getFightTeamGetByPoolRunIdIdOffsetLimit>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFightTeamGetByPoolRunIdIdOffsetLimit<
  TData = Awaited<ReturnType<typeof getFightTeamGetByPoolRunIdIdOffsetLimit>>,
  TError = void,
>(
  id: string,
  offset: string,
  limit: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightTeamGetByPoolRunIdIdOffsetLimit>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFightTeamGetByPoolRunIdIdOffsetLimit>>,
          TError,
          Awaited<ReturnType<typeof getFightTeamGetByPoolRunIdIdOffsetLimit>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFightTeamGetByPoolRunIdIdOffsetLimit<
  TData = Awaited<ReturnType<typeof getFightTeamGetByPoolRunIdIdOffsetLimit>>,
  TError = void,
>(
  id: string,
  offset: string,
  limit: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightTeamGetByPoolRunIdIdOffsetLimit>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get fights by pool run ID
 */

export function useGetFightTeamGetByPoolRunIdIdOffsetLimit<
  TData = Awaited<ReturnType<typeof getFightTeamGetByPoolRunIdIdOffsetLimit>>,
  TError = void,
>(
  id: string,
  offset: string,
  limit: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightTeamGetByPoolRunIdIdOffsetLimit>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetFightTeamGetByPoolRunIdIdOffsetLimitQueryOptions(
    id,
    offset,
    limit,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Retrieves the count of fights associated with a specific pool run ID.
 * @summary Get fight count by pool run ID
 */
export const getFightTeamGetCountByPoolRunIdId = (
  id: string,
  signal?: AbortSignal,
) => {
  return apiClient<GetCountByPoolRunIdResponse>({
    url: `/fight/team/get-count-by-pool-run-id/${id}`,
    method: 'GET',
    signal,
  });
};

export const getGetFightTeamGetCountByPoolRunIdIdQueryKey = (id: string) => {
  return [`/fight/team/get-count-by-pool-run-id/${id}`] as const;
};

export const getGetFightTeamGetCountByPoolRunIdIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getFightTeamGetCountByPoolRunIdId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightTeamGetCountByPoolRunIdId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetFightTeamGetCountByPoolRunIdIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getFightTeamGetCountByPoolRunIdId>>
  > = ({ signal }) => getFightTeamGetCountByPoolRunIdId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getFightTeamGetCountByPoolRunIdId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetFightTeamGetCountByPoolRunIdIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFightTeamGetCountByPoolRunIdId>>
>;
export type GetFightTeamGetCountByPoolRunIdIdQueryError = void;

export function useGetFightTeamGetCountByPoolRunIdId<
  TData = Awaited<ReturnType<typeof getFightTeamGetCountByPoolRunIdId>>,
  TError = void,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightTeamGetCountByPoolRunIdId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFightTeamGetCountByPoolRunIdId>>,
          TError,
          Awaited<ReturnType<typeof getFightTeamGetCountByPoolRunIdId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFightTeamGetCountByPoolRunIdId<
  TData = Awaited<ReturnType<typeof getFightTeamGetCountByPoolRunIdId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightTeamGetCountByPoolRunIdId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFightTeamGetCountByPoolRunIdId>>,
          TError,
          Awaited<ReturnType<typeof getFightTeamGetCountByPoolRunIdId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFightTeamGetCountByPoolRunIdId<
  TData = Awaited<ReturnType<typeof getFightTeamGetCountByPoolRunIdId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightTeamGetCountByPoolRunIdId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get fight count by pool run ID
 */

export function useGetFightTeamGetCountByPoolRunIdId<
  TData = Awaited<ReturnType<typeof getFightTeamGetCountByPoolRunIdId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightTeamGetCountByPoolRunIdId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetFightTeamGetCountByPoolRunIdIdQueryOptions(
    id,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
