/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Leekwars Tools API
 * OpenAPI spec version: 4.2.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import type {
  CheckPathRequest,
  CheckPathResponse,
  GetTopLevelResponse,
  StatusPorcelainResponse,
} from '../leekwarsToolsAPI.schemas';

import { apiClient } from '.././lib/api-client';

/**
 * Checks whether a specific file belongs to a Git repository.
 * @summary Check if path is tracked by Git
 */
export const postGitCheckPath = (
  checkPathRequest: CheckPathRequest,
  signal?: AbortSignal,
) => {
  return apiClient<CheckPathResponse>({
    url: `/git/check-path`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: checkPathRequest,
    signal,
  });
};

export const getPostGitCheckPathMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postGitCheckPath>>,
    TError,
    { data: CheckPathRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postGitCheckPath>>,
  TError,
  { data: CheckPathRequest },
  TContext
> => {
  const mutationKey = ['postGitCheckPath'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postGitCheckPath>>,
    { data: CheckPathRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postGitCheckPath(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostGitCheckPathMutationResult = NonNullable<
  Awaited<ReturnType<typeof postGitCheckPath>>
>;
export type PostGitCheckPathMutationBody = CheckPathRequest;
export type PostGitCheckPathMutationError = void;

/**
 * @summary Check if path is tracked by Git
 */
export const usePostGitCheckPath = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postGitCheckPath>>,
      TError,
      { data: CheckPathRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postGitCheckPath>>,
  TError,
  { data: CheckPathRequest },
  TContext
> => {
  return useMutation(getPostGitCheckPathMutationOptions(options), queryClient);
};
/**
 * Returns the top-level directory of a Git repository.
 * @summary Get Git top-level directory
 */
export const postGitGetTopLevel = (
  checkPathRequest: CheckPathRequest,
  signal?: AbortSignal,
) => {
  return apiClient<GetTopLevelResponse>({
    url: `/git/get-top-level`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: checkPathRequest,
    signal,
  });
};

export const getPostGitGetTopLevelMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postGitGetTopLevel>>,
    TError,
    { data: CheckPathRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postGitGetTopLevel>>,
  TError,
  { data: CheckPathRequest },
  TContext
> => {
  const mutationKey = ['postGitGetTopLevel'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postGitGetTopLevel>>,
    { data: CheckPathRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postGitGetTopLevel(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostGitGetTopLevelMutationResult = NonNullable<
  Awaited<ReturnType<typeof postGitGetTopLevel>>
>;
export type PostGitGetTopLevelMutationBody = CheckPathRequest;
export type PostGitGetTopLevelMutationError = void;

/**
 * @summary Get Git top-level directory
 */
export const usePostGitGetTopLevel = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postGitGetTopLevel>>,
      TError,
      { data: CheckPathRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postGitGetTopLevel>>,
  TError,
  { data: CheckPathRequest },
  TContext
> => {
  return useMutation(
    getPostGitGetTopLevelMutationOptions(options),
    queryClient,
  );
};
/**
 * Returns the Git status of a repository in porcelain format.
 * @summary Get Git status in porcelain format
 */
export const postGitStatusPorcelain = (
  checkPathRequest: CheckPathRequest,
  signal?: AbortSignal,
) => {
  return apiClient<StatusPorcelainResponse>({
    url: `/git/status-porcelain`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: checkPathRequest,
    signal,
  });
};

export const getPostGitStatusPorcelainMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postGitStatusPorcelain>>,
    TError,
    { data: CheckPathRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postGitStatusPorcelain>>,
  TError,
  { data: CheckPathRequest },
  TContext
> => {
  const mutationKey = ['postGitStatusPorcelain'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postGitStatusPorcelain>>,
    { data: CheckPathRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postGitStatusPorcelain(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostGitStatusPorcelainMutationResult = NonNullable<
  Awaited<ReturnType<typeof postGitStatusPorcelain>>
>;
export type PostGitStatusPorcelainMutationBody = CheckPathRequest;
export type PostGitStatusPorcelainMutationError = void;

/**
 * @summary Get Git status in porcelain format
 */
export const usePostGitStatusPorcelain = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postGitStatusPorcelain>>,
      TError,
      { data: CheckPathRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postGitStatusPorcelain>>,
  TError,
  { data: CheckPathRequest },
  TContext
> => {
  return useMutation(
    getPostGitStatusPorcelainMutationOptions(options),
    queryClient,
  );
};
