/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Leekwars Tools API
 * OpenAPI spec version: 4.2.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  AddFarmerRequest,
  AddFarmerResponse,
  GetAllFarmersResponse,
} from '../leekwarsToolsAPI.schemas';

import { apiClient } from '.././lib/api-client';

/**
 * Adds a new farmer to the system.
 * @summary Add a farmer
 */
export const postFarmersAdd = (
  addFarmerRequest: AddFarmerRequest,
  signal?: AbortSignal,
) => {
  return apiClient<AddFarmerResponse>({
    url: `/farmers/add`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: addFarmerRequest,
    signal,
  });
};

export const getPostFarmersAddMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postFarmersAdd>>,
    TError,
    { data: AddFarmerRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postFarmersAdd>>,
  TError,
  { data: AddFarmerRequest },
  TContext
> => {
  const mutationKey = ['postFarmersAdd'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postFarmersAdd>>,
    { data: AddFarmerRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postFarmersAdd(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostFarmersAddMutationResult = NonNullable<
  Awaited<ReturnType<typeof postFarmersAdd>>
>;
export type PostFarmersAddMutationBody = AddFarmerRequest;
export type PostFarmersAddMutationError = void;

/**
 * @summary Add a farmer
 */
export const usePostFarmersAdd = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postFarmersAdd>>,
      TError,
      { data: AddFarmerRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postFarmersAdd>>,
  TError,
  { data: AddFarmerRequest },
  TContext
> => {
  return useMutation(getPostFarmersAddMutationOptions(options), queryClient);
};
/**
 * Returns a list of all farmers.
 * @summary Get all farmers
 */
export const getFarmersAll = (signal?: AbortSignal) => {
  return apiClient<GetAllFarmersResponse>({
    url: `/farmers/all`,
    method: 'GET',
    signal,
  });
};

export const getGetFarmersAllQueryKey = () => {
  return [`/farmers/all`] as const;
};

export const getGetFarmersAllQueryOptions = <
  TData = Awaited<ReturnType<typeof getFarmersAll>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getFarmersAll>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetFarmersAllQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getFarmersAll>>> = ({
    signal,
  }) => getFarmersAll(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getFarmersAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetFarmersAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFarmersAll>>
>;
export type GetFarmersAllQueryError = void;

export function useGetFarmersAll<
  TData = Awaited<ReturnType<typeof getFarmersAll>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFarmersAll>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFarmersAll>>,
          TError,
          Awaited<ReturnType<typeof getFarmersAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFarmersAll<
  TData = Awaited<ReturnType<typeof getFarmersAll>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFarmersAll>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFarmersAll>>,
          TError,
          Awaited<ReturnType<typeof getFarmersAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFarmersAll<
  TData = Awaited<ReturnType<typeof getFarmersAll>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFarmersAll>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all farmers
 */

export function useGetFarmersAll<
  TData = Awaited<ReturnType<typeof getFarmersAll>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFarmersAll>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetFarmersAllQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
