/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Leekwars Tools API
 * OpenAPI spec version: 4.2.0
 */
export interface AddAIRequest {
  name?: string;
  description?: string;
  relativeFilePath?: string;
}

export interface AnalyzeAIRequest {
  filePath?: string;
}

export interface GitInfosResponse {
  repoUrl: string;
  branchName: string;
  commitHash: string;
  mainFileRelativePath: string;
}

export interface EntityAIResponse {
  id: string;
  name: string;
  description: string;
  gitInfos: GitInfosResponse;
}

export interface AddAIResponse {
  ai: EntityAIResponse;
}

export interface AnalyzeAIResponse {
  success: boolean;
  errorCount: number;
}

export interface ListAIResponse {
  ais: EntityAIResponse[];
}

export interface AddLeekToDuelPoolRequest {
  leekId?: string;
}

export interface CreateBasePoolRequest {
  deterministic: boolean;
  enabled: boolean;
  fightLimit: number;
  fightLimitEnabled: boolean;
  name?: string;
  resetElo: boolean;
  startSeed: number;
}

export interface CreateDuelPoolRequest {
  leekIds?: string[];
  basePoolRequest?: CreateBasePoolRequest;
}

export interface RemoveLeekFromDuelPoolRequest {
  leekId?: string;
}

/**
 * Represents a base pool returned by the API
 */
export interface BasePoolResponse {
  id: string;
  name: string;
  enabled: boolean;
  resetElo: boolean;
  deterministic: boolean;
  startSeed: number;
  fightLimitEnabled: boolean;
  fightLimit: number;
  creationDate: number;
  lastUpdateDate: number;
}

export interface EntityStats {
  agility: number;
  cores: number;
  frequency: number;
  life: number;
  magic: number;
  mp: number;
  ram: number;
  resistance: number;
  science: number;
  strength: number;
  tp: number;
  wisdom: number;
}

export interface EntityBuild {
  investedCapital: number;
  equippedComponentIds: number[];
  bonusStats: EntityStats;
  investedStats: EntityStats;
  totalStats: EntityStats;
  level: number;
  selectedChipIds: number[];
  selectedWeaponIds: number[];
  totalCapital: number;
}

export interface LeekResponse {
  id: string;
  name: string;
  imageName: string;
  build: EntityBuild;
  ai: EntityAIResponse;
  creationDate: number;
}

export interface DuelPoolResponse {
  id: string;
  basePool: BasePoolResponse;
  leeks: LeekResponse[];
}

export interface GetDuelPoolsResponse {
  pools: DuelPoolResponse[];
}

export interface PoolLeekResponse {
  id: string;
  originalLeekId: string;
  name: string;
  imageName: string;
  build: EntityBuild;
  ai: EntityAIResponse;
  elo: number;
}

export interface DuelPoolRunResponse {
  id: string;
  interrupted: boolean;
  running: boolean;
  basePool: BasePoolResponse;
  startDate: number;
  endDate: number;
  leeks: PoolLeekResponse[];
  duelPoolId: string;
}

export interface ListDuelPoolRunResponse {
  runs: DuelPoolRunResponse[];
}

export interface GenerateFightRequest {
  fightId: string;
}

export interface GenerateFightResponse {
  fightId: string;
}

export interface BrowseDirectoryRequest {
  directoryPath: string;
}

export interface FileInfo {
  name?: string;
  path?: string;
  directory: boolean;
  size: number;
  lastModified: number;
  creationTime: number;
  readable: boolean;
  writable: boolean;
  hidden: boolean;
  extension?: string;
  formattedSize?: string;
}

export interface BrowseDirectoryResponse {
  files: FileInfo[];
  currentDirectory: string;
}

export interface CheckPathRequest {
  filePath?: string;
}

export interface CheckPathResponse {
  exists: boolean;
}

export interface GetTopLevelResponse {
  topLevel: string;
}

export interface GitPorcelainItem {
  path?: string;
  status?: string;
}

export interface StatusPorcelainResponse {
  items: GitPorcelainItem[];
}

export interface AddLeekRequest {
  name?: string;
  build?: EntityBuild;
  imageName?: string;
  aiId?: string;
}

export interface AddLeekResponse {
  leek: LeekResponse;
}

export interface GetAllLeeksResponse {
  leeks: LeekResponse[];
}

export interface SetBooleanRequest {
  value: boolean;
}

export interface SetIntegerRequest {
  value: number;
}

export interface UpdatePoolNameRequest {
  name?: string;
}

/**
 * Represents a response containing a list of base pools returned by the API
 */
export interface GetBasePoolsResponse {
  pools: BasePoolResponse[];
}

export type GetApiFightGetByPoolRunIdId200Item = { [key: string]: unknown };
