/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Leekwars Tools API
 * OpenAPI spec version: 4.2.0
 */
export interface AddAIRequest {
  name?: string;
  description?: string;
  relativeFilePath?: string;
}

export interface AnalyzeAIRequest {
  filePath?: string;
}

export interface RenameAIRequest {
  newName: string;
}

export interface GitInfosResponse {
  repoUrl: string;
  branchName: string;
  commitHash: string;
  mainFileRelativePath: string;
}

export interface EntityAIResponse {
  id: string;
  name: string;
  description: string;
  gitInfos: GitInfosResponse;
}

export interface AddAIResponse {
  ai: EntityAIResponse;
}

export interface AnalyzeAIResponse {
  success: boolean;
  errorCount: number;
}

export interface ListAIResponse {
  ais: EntityAIResponse[];
}

export interface RunningPoolResponse {
  poolRunId: string;
  poolId: string;
  name: string;
  type: string;
  startTime: number;
  totalFights: number;
  completedFights: number;
}

export interface GetAllRunningPoolsResponse {
  runningPools: RunningPoolResponse[];
}

export interface BasePoolStopResponse {
  success: boolean;
}

export interface PoolFightDuelResponse {
  id: string;
  poolRunId: string;
  seed: number;
  date: number;
  leek1Id: string;
  leek2Id: string;
  winnerLeekId?: string;
}

export interface GetDuelFightsByPoolRunIdResponse {
  fights: PoolFightDuelResponse[];
}

export interface AddLeekToDuelPoolRequest {
  leekId?: string;
}

export interface CreateBasePoolRequest {
  deterministic: boolean;
  enabled: boolean;
  fightLimit: number;
  fightLimitEnabled: boolean;
  name?: string;
  resetElo: boolean;
  startSeed: number;
}

export interface CreateDuelPoolRequest {
  leekIds?: string[];
  basePoolRequest?: CreateBasePoolRequest;
}

export interface RemoveLeekFromDuelPoolRequest {
  leekId?: string;
}

/**
 * Represents a base pool returned by the API
 */
export interface BasePoolResponse {
  id: string;
  name: string;
  enabled: boolean;
  resetElo: boolean;
  deterministic: boolean;
  startSeed: number;
  fightLimitEnabled: boolean;
  fightLimit: number;
  creationDate: number;
  lastUpdateDate: number;
}

export interface EntityStats {
  agility: number;
  cores: number;
  frequency: number;
  life: number;
  magic: number;
  mp: number;
  ram: number;
  resistance: number;
  science: number;
  strength: number;
  tp: number;
  wisdom: number;
}

export interface EntityBuild {
  investedCapital: number;
  equippedComponentIds: number[];
  bonusStats: EntityStats;
  investedStats: EntityStats;
  level: number;
  selectedChipIds: number[];
  selectedWeaponIds: number[];
  totalCapital: number;
}

export interface LeekResponse {
  id: string;
  name: string;
  imageName: string;
  build: EntityBuild;
  ai: EntityAIResponse;
  creationDate: number;
}

export interface PoolRunsInfoResponse {
  runCount: number;
  lastRunId?: string;
  lastRunIsRunning: boolean;
}

export interface DuelPoolResponse {
  id: string;
  basePool: BasePoolResponse;
  leeks: LeekResponse[];
  poolRunsInfo: PoolRunsInfoResponse;
}

export interface GetDuelPoolsResponse {
  pools: DuelPoolResponse[];
}

export interface PoolLeekResponse {
  id: string;
  originalLeekId: string;
  name: string;
  imageName: string;
  build: EntityBuild;
  ai: EntityAIResponse;
  elo: number;
}

export interface DuelPoolRunResponse {
  id: string;
  interrupted: boolean;
  running: boolean;
  basePool: BasePoolResponse;
  startDate: number;
  endDate: number;
  leeks: PoolLeekResponse[];
  duelPoolId: string;
}

export interface ListDuelPoolRunResponse {
  runs: DuelPoolRunResponse[];
}

export interface AddFarmerRequest {
  name: string;
  leekIds: string[];
}

export interface FarmerResponse {
  id: string;
  name: string;
  creationDate: number;
  lastUpdateDate: number;
  leeks: LeekResponse[];
}

export interface AddFarmerResponse {
  farmer: FarmerResponse;
}

export interface GetAllFarmersResponse {
  farmers: FarmerResponse[];
}

export interface PoolFightFarmerResponse {
  id: string;
  poolRunId: string;
  seed: number;
  date: number;
  farmer1Id: string;
  farmer2Id: string;
  winnerFarmerId?: string;
}

export interface GetFarmerFightsByPoolRunIdResponse {
  fights: PoolFightFarmerResponse[];
}

export interface AddFarmerToPoolRequest {
  farmerId?: string;
}

export interface CreateFarmerPoolRequest {
  farmerIds?: string[];
  basePoolRequest?: CreateBasePoolRequest;
}

export interface FarmerPoolResponse {
  id: string;
  basePool: BasePoolResponse;
  farmers: FarmerResponse[];
  poolRunsInfo: PoolRunsInfoResponse;
}

export interface GetAllFarmerPoolsResponse {
  farmerPools: FarmerPoolResponse[];
}

export interface PoolFarmerResponse {
  id: string;
  name: string;
  leeks: PoolLeekResponse[];
  elo: number;
}

export interface FarmerPoolRunResponse {
  id: string;
  interrupted: boolean;
  running: boolean;
  basePool: BasePoolResponse;
  startDate: number;
  endDate: number;
  farmerPoolId: string;
  farmers: PoolFarmerResponse[];
}

export interface ListFarmerPoolRunResponse {
  runs: FarmerPoolRunResponse[];
}

export interface GenerateFightRequest {
  fightId: string;
}

export interface GenerateFightResponse {
  fightId: string;
}

export interface GetCountByPoolRunIdResponse {
  count: number;
}

export interface PoolFightRatioResponse {
  wins: number;
  losses: number;
  draws: number;
  ownerId?: string;
}

export interface PoolFightRatioListResponse {
  ratios?: PoolFightRatioResponse[];
}

export interface BrowseDirectoryRequest {
  directoryPath: string;
}

export interface FileInfo {
  name?: string;
  path?: string;
  directory: boolean;
  size: number;
  lastModified: number;
  creationTime: number;
  readable: boolean;
  writable: boolean;
  hidden: boolean;
  extension?: string;
  formattedSize?: string;
}

export interface BrowseDirectoryResponse {
  files: FileInfo[];
  currentDirectory: string;
}

export interface CheckPathRequest {
  filePath?: string;
}

export interface CheckPathResponse {
  exists: boolean;
}

export interface GetTopLevelResponse {
  topLevel: string;
}

export interface GitPorcelainItem {
  path?: string;
  status?: string;
}

export interface StatusPorcelainResponse {
  items: GitPorcelainItem[];
}

export interface MatrixHeatmapEntity {
  id: string;
  label: string;
}

export interface MatrixHeatmapPair {
  from: MatrixHeatmapEntity;
  to: MatrixHeatmapEntity;
  value: number;
}

export interface DuelPoolLeekMatrixHeatmapResponse {
  pairs: MatrixHeatmapPair[];
}

export interface FarmerPoolMatrixHeatmapResponse {
  pairs: MatrixHeatmapPair[];
}

export interface TeamPoolMatrixHeatmapResponse {
  pairs: MatrixHeatmapPair[];
}

export interface AddLeekRequest {
  name: string;
  build: EntityBuild;
  imageName: string;
  aiId: string;
}

export interface AddLeekResponse {
  leek: LeekResponse;
}

export interface GetAllLeeksResponse {
  leeks: LeekResponse[];
}

export interface AddLeekGroupRequest {
  name: string;
  leekIds: string[];
}

export interface LeekGroupResponse {
  id: string;
  name: string;
  leeks: LeekResponse[];
}

export interface AddLeekGroupResponse {
  leekGroup?: LeekGroupResponse;
}

export interface GetAllLeekGroupsResponse {
  leekGroups: LeekGroupResponse[];
}

export interface AddMobRequest {
  name: string;
  internalName: string;
  type: string;
  build: EntityBuild;
  aiId: string;
}

export interface MobResponse {
  id: string;
  name: string;
  internalName: string;
  type: string;
  build: EntityBuild;
  ai: EntityAIResponse;
  creationDate: number;
}

export interface AddMobResponse {
  mob: MobResponse;
}

export interface GetAllMobsResponse {
  mobs: MobResponse[];
}

export interface SetBooleanRequest {
  value: boolean;
}

export interface SetIntegerRequest {
  value: number;
}

export interface UpdatePoolNameRequest {
  name?: string;
}

/**
 * Represents a response containing a list of base pools returned by the API
 */
export interface GetBasePoolsResponse {
  pools: BasePoolResponse[];
}

export interface PoolLeekGroupResponse {
  id: string;
  originalLeekGroupId: string;
  leeks: PoolLeekResponse[];
  name: string;
  elo: number;
}

export interface PoolMobResponse {
  id: string;
  originalMobId: string;
  name: string;
  internalName: string;
  type: string;
  build: EntityBuild;
  ai: EntityAIResponse;
}

export interface TurretResponse {
  id: string;
  name: string;
  build: EntityBuild;
  ai: EntityAIResponse;
  creationDate: number;
  lastUpdateDate: number;
}

export interface PoolTeamResponse {
  id: string;
  name: string;
  leeks: PoolLeekResponse[];
  turret: TurretResponse;
  elo: number;
}

export interface PoolFightPumpkinResponse {
  id: string;
  poolRunId: string;
  seed: number;
  date: number;
  leekGroupId: string;
  result: string;
}

export interface GetPumpkinFightsByPoolRunIdResponse {
  fights: PoolFightPumpkinResponse[];
}

export interface CreatePumpkinPoolRequest {
  leekGroupIds: string[];
  mobIds: string[];
  basePoolRequest: CreateBasePoolRequest;
}

export interface PumpkinPoolResponse {
  id: string;
  basePool: BasePoolResponse;
  mobs: MobResponse[];
  leekGroups: LeekGroupResponse[];
  poolRunsInfo: PoolRunsInfoResponse;
}

export interface GetAllPumpkinPoolsResponse {
  pumpkinPools: PumpkinPoolResponse[];
}

export interface PumpkinPoolRunResponse {
  id: string;
  interrupted: boolean;
  running: boolean;
  basePool: BasePoolResponse;
  startDate: number;
  endDate: number;
  leekGroups: PoolLeekGroupResponse[];
  mobs: PoolMobResponse[];
  pumpkinPoolId: string;
}

export interface ListPumpkinPoolRunResponse {
  runs: PumpkinPoolRunResponse[];
}

export interface AddTeamRequest {
  name: string;
  leekIds: string[];
  turretId: string;
}

export interface TeamResponse {
  id: string;
  name: string;
  creationDate: number;
  lastUpdateDate: number;
  leeks: LeekResponse[];
  turret: TurretResponse;
}

export interface AddTeamResponse {
  team: TeamResponse;
}

export interface GetAllTeamsResponse {
  teams: TeamResponse[];
}

export interface PoolFightTeamResponse {
  id: string;
  poolRunId: string;
  seed: number;
  date: number;
  team1Id: string;
  team2Id: string;
  winnerTeamId: string;
}

export interface GetTeamFightsByPoolRunIdResponse {
  fights: PoolFightTeamResponse[];
}

export interface AddTeamToPoolRequest {
  teamId?: string;
}

export interface CreateTeamPoolRequest {
  teamIds: string[];
  basePoolRequest: CreateBasePoolRequest;
}

export interface TeamPoolResponse {
  id: string;
  basePool: BasePoolResponse;
  teams: TeamResponse[];
  poolRunsInfo: PoolRunsInfoResponse;
}

export interface GetAllTeamPoolsResponse {
  teamPools: TeamPoolResponse[];
}

export interface TeamPoolRunResponse {
  id: string;
  interrupted: boolean;
  running: boolean;
  basePool: BasePoolResponse;
  startDate: number;
  endDate: number;
  teamPoolId?: string;
  teams?: PoolTeamResponse[];
}

export interface ListTeamPoolRunResponse {
  runs: TeamPoolRunResponse[];
}

export interface AddTurretRequest {
  name: string;
  build: EntityBuild;
  aiId: string;
}

export interface GetAllTurretsResponse {
  turrets: TurretResponse[];
}
