/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Leekwars Tools API
 * OpenAPI spec version: 4.2.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  AddLeekGroupRequest,
  AddLeekGroupResponse,
  GetAllLeekGroupsResponse,
  LeekGroupResponse,
} from '../leekwarsToolsAPI.schemas';

import { apiClient } from '.././lib/api-client';

/**
 * Adds a new leek group to the system.
 * @summary Add a leek group
 */
export const postLeekGroupsAdd = (
  addLeekGroupRequest: AddLeekGroupRequest,
  signal?: AbortSignal,
) => {
  return apiClient<AddLeekGroupResponse>({
    url: `/leek-groups/add`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: addLeekGroupRequest,
    signal,
  });
};

export const getPostLeekGroupsAddMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postLeekGroupsAdd>>,
    TError,
    { data: AddLeekGroupRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postLeekGroupsAdd>>,
  TError,
  { data: AddLeekGroupRequest },
  TContext
> => {
  const mutationKey = ['postLeekGroupsAdd'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postLeekGroupsAdd>>,
    { data: AddLeekGroupRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postLeekGroupsAdd(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostLeekGroupsAddMutationResult = NonNullable<
  Awaited<ReturnType<typeof postLeekGroupsAdd>>
>;
export type PostLeekGroupsAddMutationBody = AddLeekGroupRequest;
export type PostLeekGroupsAddMutationError = void;

/**
 * @summary Add a leek group
 */
export const usePostLeekGroupsAdd = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postLeekGroupsAdd>>,
      TError,
      { data: AddLeekGroupRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postLeekGroupsAdd>>,
  TError,
  { data: AddLeekGroupRequest },
  TContext
> => {
  return useMutation(getPostLeekGroupsAddMutationOptions(options), queryClient);
};
/**
 * Returns a list of all leek groups.
 * @summary Get all leek groups
 */
export const getLeekGroupsAll = (signal?: AbortSignal) => {
  return apiClient<GetAllLeekGroupsResponse>({
    url: `/leek-groups/all`,
    method: 'GET',
    signal,
  });
};

export const getGetLeekGroupsAllQueryKey = () => {
  return [`/leek-groups/all`] as const;
};

export const getGetLeekGroupsAllQueryOptions = <
  TData = Awaited<ReturnType<typeof getLeekGroupsAll>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getLeekGroupsAll>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetLeekGroupsAllQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getLeekGroupsAll>>
  > = ({ signal }) => getLeekGroupsAll(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getLeekGroupsAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetLeekGroupsAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof getLeekGroupsAll>>
>;
export type GetLeekGroupsAllQueryError = void;

export function useGetLeekGroupsAll<
  TData = Awaited<ReturnType<typeof getLeekGroupsAll>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLeekGroupsAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLeekGroupsAll>>,
          TError,
          Awaited<ReturnType<typeof getLeekGroupsAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetLeekGroupsAll<
  TData = Awaited<ReturnType<typeof getLeekGroupsAll>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLeekGroupsAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLeekGroupsAll>>,
          TError,
          Awaited<ReturnType<typeof getLeekGroupsAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetLeekGroupsAll<
  TData = Awaited<ReturnType<typeof getLeekGroupsAll>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLeekGroupsAll>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all leek groups
 */

export function useGetLeekGroupsAll<
  TData = Awaited<ReturnType<typeof getLeekGroupsAll>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLeekGroupsAll>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetLeekGroupsAllQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Removes a leek group from the system.
 * @summary Remove a leek group
 */
export const deleteLeekGroupsDeleteLeekGroupId = (
  leekGroupId: string,
  signal?: AbortSignal,
) => {
  return apiClient<void>({
    url: `/leek-groups/delete/${leekGroupId}`,
    method: 'DELETE',
    signal,
  });
};

export const getDeleteLeekGroupsDeleteLeekGroupIdMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteLeekGroupsDeleteLeekGroupId>>,
    TError,
    { leekGroupId: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteLeekGroupsDeleteLeekGroupId>>,
  TError,
  { leekGroupId: string },
  TContext
> => {
  const mutationKey = ['deleteLeekGroupsDeleteLeekGroupId'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteLeekGroupsDeleteLeekGroupId>>,
    { leekGroupId: string }
  > = (props) => {
    const { leekGroupId } = props ?? {};

    return deleteLeekGroupsDeleteLeekGroupId(leekGroupId);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteLeekGroupsDeleteLeekGroupIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteLeekGroupsDeleteLeekGroupId>>
>;

export type DeleteLeekGroupsDeleteLeekGroupIdMutationError = void;

/**
 * @summary Remove a leek group
 */
export const useDeleteLeekGroupsDeleteLeekGroupId = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteLeekGroupsDeleteLeekGroupId>>,
      TError,
      { leekGroupId: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteLeekGroupsDeleteLeekGroupId>>,
  TError,
  { leekGroupId: string },
  TContext
> => {
  return useMutation(
    getDeleteLeekGroupsDeleteLeekGroupIdMutationOptions(options),
    queryClient,
  );
};
/**
 * Adds a leek to a leek group.
 * @summary Add a leek to a leek group
 */
export const postLeekGroupsLeekGroupIdAddLeekLeekId = (
  leekGroupId: string,
  leekId: string,
  signal?: AbortSignal,
) => {
  return apiClient<LeekGroupResponse>({
    url: `/leek-groups/${leekGroupId}/add-leek/${leekId}`,
    method: 'POST',
    signal,
  });
};

export const getPostLeekGroupsLeekGroupIdAddLeekLeekIdMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postLeekGroupsLeekGroupIdAddLeekLeekId>>,
    TError,
    { leekGroupId: string; leekId: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postLeekGroupsLeekGroupIdAddLeekLeekId>>,
  TError,
  { leekGroupId: string; leekId: string },
  TContext
> => {
  const mutationKey = ['postLeekGroupsLeekGroupIdAddLeekLeekId'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postLeekGroupsLeekGroupIdAddLeekLeekId>>,
    { leekGroupId: string; leekId: string }
  > = (props) => {
    const { leekGroupId, leekId } = props ?? {};

    return postLeekGroupsLeekGroupIdAddLeekLeekId(leekGroupId, leekId);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostLeekGroupsLeekGroupIdAddLeekLeekIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof postLeekGroupsLeekGroupIdAddLeekLeekId>>
>;

export type PostLeekGroupsLeekGroupIdAddLeekLeekIdMutationError = void;

/**
 * @summary Add a leek to a leek group
 */
export const usePostLeekGroupsLeekGroupIdAddLeekLeekId = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postLeekGroupsLeekGroupIdAddLeekLeekId>>,
      TError,
      { leekGroupId: string; leekId: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postLeekGroupsLeekGroupIdAddLeekLeekId>>,
  TError,
  { leekGroupId: string; leekId: string },
  TContext
> => {
  return useMutation(
    getPostLeekGroupsLeekGroupIdAddLeekLeekIdMutationOptions(options),
    queryClient,
  );
};
/**
 * Removes a leek from a leek group.
 * @summary Remove a leek from a leek group
 */
export const deleteLeekGroupsLeekGroupIdRemoveLeekLeekId = (
  leekGroupId: string,
  leekId: string,
  signal?: AbortSignal,
) => {
  return apiClient<LeekGroupResponse>({
    url: `/leek-groups/${leekGroupId}/remove-leek/${leekId}`,
    method: 'DELETE',
    signal,
  });
};

export const getDeleteLeekGroupsLeekGroupIdRemoveLeekLeekIdMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteLeekGroupsLeekGroupIdRemoveLeekLeekId>>,
    TError,
    { leekGroupId: string; leekId: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteLeekGroupsLeekGroupIdRemoveLeekLeekId>>,
  TError,
  { leekGroupId: string; leekId: string },
  TContext
> => {
  const mutationKey = ['deleteLeekGroupsLeekGroupIdRemoveLeekLeekId'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteLeekGroupsLeekGroupIdRemoveLeekLeekId>>,
    { leekGroupId: string; leekId: string }
  > = (props) => {
    const { leekGroupId, leekId } = props ?? {};

    return deleteLeekGroupsLeekGroupIdRemoveLeekLeekId(leekGroupId, leekId);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteLeekGroupsLeekGroupIdRemoveLeekLeekIdMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof deleteLeekGroupsLeekGroupIdRemoveLeekLeekId>>
  >;

export type DeleteLeekGroupsLeekGroupIdRemoveLeekLeekIdMutationError = void;

/**
 * @summary Remove a leek from a leek group
 */
export const useDeleteLeekGroupsLeekGroupIdRemoveLeekLeekId = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteLeekGroupsLeekGroupIdRemoveLeekLeekId>>,
      TError,
      { leekGroupId: string; leekId: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteLeekGroupsLeekGroupIdRemoveLeekLeekId>>,
  TError,
  { leekGroupId: string; leekId: string },
  TContext
> => {
  return useMutation(
    getDeleteLeekGroupsLeekGroupIdRemoveLeekLeekIdMutationOptions(options),
    queryClient,
  );
};
