/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Leekwars Tools API
 * OpenAPI spec version: 4.2.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  GenerateFightRequest,
  GenerateFightResponse,
  GetCountByPoolRunIdResponse,
  GetFarmerFightsByPoolRunIdResponse,
} from '../leekwarsToolsAPI.schemas';

import { apiClient } from '.././lib/api-client';

/**
 * Generates a fight based on the provided fight ID. The fight ID should correspond to an existing fight in the system.
 * @summary Generate a fight
 */
export const postFightFarmerGenerate = (
  generateFightRequest: GenerateFightRequest,
  signal?: AbortSignal,
) => {
  return apiClient<GenerateFightResponse>({
    url: `/fight/farmer/generate`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: generateFightRequest,
    signal,
  });
};

export const getPostFightFarmerGenerateMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postFightFarmerGenerate>>,
    TError,
    { data: GenerateFightRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postFightFarmerGenerate>>,
  TError,
  { data: GenerateFightRequest },
  TContext
> => {
  const mutationKey = ['postFightFarmerGenerate'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postFightFarmerGenerate>>,
    { data: GenerateFightRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postFightFarmerGenerate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostFightFarmerGenerateMutationResult = NonNullable<
  Awaited<ReturnType<typeof postFightFarmerGenerate>>
>;
export type PostFightFarmerGenerateMutationBody = GenerateFightRequest;
export type PostFightFarmerGenerateMutationError = void;

/**
 * @summary Generate a fight
 */
export const usePostFightFarmerGenerate = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postFightFarmerGenerate>>,
      TError,
      { data: GenerateFightRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postFightFarmerGenerate>>,
  TError,
  { data: GenerateFightRequest },
  TContext
> => {
  return useMutation(
    getPostFightFarmerGenerateMutationOptions(options),
    queryClient,
  );
};
/**
 * Retrieves a list of fights associated with a specific pool run ID.
 * @summary Get fights by pool run ID
 */
export const getFightFarmerGetByPoolRunIdIdOffsetLimit = (
  id: string,
  offset: string,
  limit: string,
  signal?: AbortSignal,
) => {
  return apiClient<GetFarmerFightsByPoolRunIdResponse>({
    url: `/fight/farmer/get-by-pool-run-id/${id}/${offset}/${limit}`,
    method: 'GET',
    signal,
  });
};

export const getGetFightFarmerGetByPoolRunIdIdOffsetLimitQueryKey = (
  id: string,
  offset: string,
  limit: string,
) => {
  return [`/fight/farmer/get-by-pool-run-id/${id}/${offset}/${limit}`] as const;
};

export const getGetFightFarmerGetByPoolRunIdIdOffsetLimitQueryOptions = <
  TData = Awaited<ReturnType<typeof getFightFarmerGetByPoolRunIdIdOffsetLimit>>,
  TError = void,
>(
  id: string,
  offset: string,
  limit: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightFarmerGetByPoolRunIdIdOffsetLimit>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetFightFarmerGetByPoolRunIdIdOffsetLimitQueryKey(id, offset, limit);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getFightFarmerGetByPoolRunIdIdOffsetLimit>>
  > = ({ signal }) =>
    getFightFarmerGetByPoolRunIdIdOffsetLimit(id, offset, limit, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(id && offset && limit),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getFightFarmerGetByPoolRunIdIdOffsetLimit>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetFightFarmerGetByPoolRunIdIdOffsetLimitQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFightFarmerGetByPoolRunIdIdOffsetLimit>>
>;
export type GetFightFarmerGetByPoolRunIdIdOffsetLimitQueryError = void;

export function useGetFightFarmerGetByPoolRunIdIdOffsetLimit<
  TData = Awaited<ReturnType<typeof getFightFarmerGetByPoolRunIdIdOffsetLimit>>,
  TError = void,
>(
  id: string,
  offset: string,
  limit: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightFarmerGetByPoolRunIdIdOffsetLimit>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFightFarmerGetByPoolRunIdIdOffsetLimit>>,
          TError,
          Awaited<ReturnType<typeof getFightFarmerGetByPoolRunIdIdOffsetLimit>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFightFarmerGetByPoolRunIdIdOffsetLimit<
  TData = Awaited<ReturnType<typeof getFightFarmerGetByPoolRunIdIdOffsetLimit>>,
  TError = void,
>(
  id: string,
  offset: string,
  limit: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightFarmerGetByPoolRunIdIdOffsetLimit>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFightFarmerGetByPoolRunIdIdOffsetLimit>>,
          TError,
          Awaited<ReturnType<typeof getFightFarmerGetByPoolRunIdIdOffsetLimit>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFightFarmerGetByPoolRunIdIdOffsetLimit<
  TData = Awaited<ReturnType<typeof getFightFarmerGetByPoolRunIdIdOffsetLimit>>,
  TError = void,
>(
  id: string,
  offset: string,
  limit: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightFarmerGetByPoolRunIdIdOffsetLimit>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get fights by pool run ID
 */

export function useGetFightFarmerGetByPoolRunIdIdOffsetLimit<
  TData = Awaited<ReturnType<typeof getFightFarmerGetByPoolRunIdIdOffsetLimit>>,
  TError = void,
>(
  id: string,
  offset: string,
  limit: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightFarmerGetByPoolRunIdIdOffsetLimit>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetFightFarmerGetByPoolRunIdIdOffsetLimitQueryOptions(
    id,
    offset,
    limit,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Retrieves the count of fights associated with a specific pool run ID.
 * @summary Get fight count by pool run ID
 */
export const getFightFarmerGetCountByPoolRunIdId = (
  id: string,
  signal?: AbortSignal,
) => {
  return apiClient<GetCountByPoolRunIdResponse>({
    url: `/fight/farmer/get-count-by-pool-run-id/${id}`,
    method: 'GET',
    signal,
  });
};

export const getGetFightFarmerGetCountByPoolRunIdIdQueryKey = (id: string) => {
  return [`/fight/farmer/get-count-by-pool-run-id/${id}`] as const;
};

export const getGetFightFarmerGetCountByPoolRunIdIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getFightFarmerGetCountByPoolRunIdId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightFarmerGetCountByPoolRunIdId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetFightFarmerGetCountByPoolRunIdIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getFightFarmerGetCountByPoolRunIdId>>
  > = ({ signal }) => getFightFarmerGetCountByPoolRunIdId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getFightFarmerGetCountByPoolRunIdId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetFightFarmerGetCountByPoolRunIdIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFightFarmerGetCountByPoolRunIdId>>
>;
export type GetFightFarmerGetCountByPoolRunIdIdQueryError = void;

export function useGetFightFarmerGetCountByPoolRunIdId<
  TData = Awaited<ReturnType<typeof getFightFarmerGetCountByPoolRunIdId>>,
  TError = void,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightFarmerGetCountByPoolRunIdId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFightFarmerGetCountByPoolRunIdId>>,
          TError,
          Awaited<ReturnType<typeof getFightFarmerGetCountByPoolRunIdId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFightFarmerGetCountByPoolRunIdId<
  TData = Awaited<ReturnType<typeof getFightFarmerGetCountByPoolRunIdId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightFarmerGetCountByPoolRunIdId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFightFarmerGetCountByPoolRunIdId>>,
          TError,
          Awaited<ReturnType<typeof getFightFarmerGetCountByPoolRunIdId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFightFarmerGetCountByPoolRunIdId<
  TData = Awaited<ReturnType<typeof getFightFarmerGetCountByPoolRunIdId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightFarmerGetCountByPoolRunIdId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get fight count by pool run ID
 */

export function useGetFightFarmerGetCountByPoolRunIdId<
  TData = Awaited<ReturnType<typeof getFightFarmerGetCountByPoolRunIdId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightFarmerGetCountByPoolRunIdId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetFightFarmerGetCountByPoolRunIdIdQueryOptions(
    id,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
