/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Leekwars Tools API
 * OpenAPI spec version: 4.2.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  GetCountByPoolRunIdResponse,
  GetFarmerFightsByPoolRunIdResponse,
} from '../leekwarsToolsAPI.schemas';

import { apiClient } from '.././lib/api-client';

/**
 * Retrieves a list of fights associated with a specific pool run ID.
 * @summary Get fights by pool run ID
 */
export const getApiFightFarmerGetByPoolRunIdIdOffsetLimit = (
  id: string,
  offset: string,
  limit: string,
  signal?: AbortSignal,
) => {
  return apiClient<GetFarmerFightsByPoolRunIdResponse>({
    url: `/api/fight/farmer/get-by-pool-run-id/${id}/${offset}/${limit}`,
    method: 'GET',
    signal,
  });
};

export const getGetApiFightFarmerGetByPoolRunIdIdOffsetLimitQueryKey = (
  id: string,
  offset: string,
  limit: string,
) => {
  return [
    `/api/fight/farmer/get-by-pool-run-id/${id}/${offset}/${limit}`,
  ] as const;
};

export const getGetApiFightFarmerGetByPoolRunIdIdOffsetLimitQueryOptions = <
  TData = Awaited<
    ReturnType<typeof getApiFightFarmerGetByPoolRunIdIdOffsetLimit>
  >,
  TError = void,
>(
  id: string,
  offset: string,
  limit: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getApiFightFarmerGetByPoolRunIdIdOffsetLimit>
        >,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetApiFightFarmerGetByPoolRunIdIdOffsetLimitQueryKey(id, offset, limit);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiFightFarmerGetByPoolRunIdIdOffsetLimit>>
  > = ({ signal }) =>
    getApiFightFarmerGetByPoolRunIdIdOffsetLimit(id, offset, limit, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(id && offset && limit),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiFightFarmerGetByPoolRunIdIdOffsetLimit>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiFightFarmerGetByPoolRunIdIdOffsetLimitQueryResult =
  NonNullable<
    Awaited<ReturnType<typeof getApiFightFarmerGetByPoolRunIdIdOffsetLimit>>
  >;
export type GetApiFightFarmerGetByPoolRunIdIdOffsetLimitQueryError = void;

export function useGetApiFightFarmerGetByPoolRunIdIdOffsetLimit<
  TData = Awaited<
    ReturnType<typeof getApiFightFarmerGetByPoolRunIdIdOffsetLimit>
  >,
  TError = void,
>(
  id: string,
  offset: string,
  limit: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getApiFightFarmerGetByPoolRunIdIdOffsetLimit>
        >,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof getApiFightFarmerGetByPoolRunIdIdOffsetLimit>
          >,
          TError,
          Awaited<
            ReturnType<typeof getApiFightFarmerGetByPoolRunIdIdOffsetLimit>
          >
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiFightFarmerGetByPoolRunIdIdOffsetLimit<
  TData = Awaited<
    ReturnType<typeof getApiFightFarmerGetByPoolRunIdIdOffsetLimit>
  >,
  TError = void,
>(
  id: string,
  offset: string,
  limit: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getApiFightFarmerGetByPoolRunIdIdOffsetLimit>
        >,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof getApiFightFarmerGetByPoolRunIdIdOffsetLimit>
          >,
          TError,
          Awaited<
            ReturnType<typeof getApiFightFarmerGetByPoolRunIdIdOffsetLimit>
          >
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiFightFarmerGetByPoolRunIdIdOffsetLimit<
  TData = Awaited<
    ReturnType<typeof getApiFightFarmerGetByPoolRunIdIdOffsetLimit>
  >,
  TError = void,
>(
  id: string,
  offset: string,
  limit: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getApiFightFarmerGetByPoolRunIdIdOffsetLimit>
        >,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get fights by pool run ID
 */

export function useGetApiFightFarmerGetByPoolRunIdIdOffsetLimit<
  TData = Awaited<
    ReturnType<typeof getApiFightFarmerGetByPoolRunIdIdOffsetLimit>
  >,
  TError = void,
>(
  id: string,
  offset: string,
  limit: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getApiFightFarmerGetByPoolRunIdIdOffsetLimit>
        >,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getGetApiFightFarmerGetByPoolRunIdIdOffsetLimitQueryOptions(
      id,
      offset,
      limit,
      options,
    );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Retrieves the count of fights associated with a specific pool run ID.
 * @summary Get fight count by pool run ID
 */
export const getApiFightFarmerGetCountByPoolRunIdId = (
  id: string,
  signal?: AbortSignal,
) => {
  return apiClient<GetCountByPoolRunIdResponse>({
    url: `/api/fight/farmer/get-count-by-pool-run-id/${id}`,
    method: 'GET',
    signal,
  });
};

export const getGetApiFightFarmerGetCountByPoolRunIdIdQueryKey = (
  id: string,
) => {
  return [`/api/fight/farmer/get-count-by-pool-run-id/${id}`] as const;
};

export const getGetApiFightFarmerGetCountByPoolRunIdIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiFightFarmerGetCountByPoolRunIdId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiFightFarmerGetCountByPoolRunIdId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetApiFightFarmerGetCountByPoolRunIdIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiFightFarmerGetCountByPoolRunIdId>>
  > = ({ signal }) => getApiFightFarmerGetCountByPoolRunIdId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiFightFarmerGetCountByPoolRunIdId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiFightFarmerGetCountByPoolRunIdIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiFightFarmerGetCountByPoolRunIdId>>
>;
export type GetApiFightFarmerGetCountByPoolRunIdIdQueryError = void;

export function useGetApiFightFarmerGetCountByPoolRunIdId<
  TData = Awaited<ReturnType<typeof getApiFightFarmerGetCountByPoolRunIdId>>,
  TError = void,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiFightFarmerGetCountByPoolRunIdId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiFightFarmerGetCountByPoolRunIdId>>,
          TError,
          Awaited<ReturnType<typeof getApiFightFarmerGetCountByPoolRunIdId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiFightFarmerGetCountByPoolRunIdId<
  TData = Awaited<ReturnType<typeof getApiFightFarmerGetCountByPoolRunIdId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiFightFarmerGetCountByPoolRunIdId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiFightFarmerGetCountByPoolRunIdId>>,
          TError,
          Awaited<ReturnType<typeof getApiFightFarmerGetCountByPoolRunIdId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiFightFarmerGetCountByPoolRunIdId<
  TData = Awaited<ReturnType<typeof getApiFightFarmerGetCountByPoolRunIdId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiFightFarmerGetCountByPoolRunIdId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get fight count by pool run ID
 */

export function useGetApiFightFarmerGetCountByPoolRunIdId<
  TData = Awaited<ReturnType<typeof getApiFightFarmerGetCountByPoolRunIdId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiFightFarmerGetCountByPoolRunIdId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiFightFarmerGetCountByPoolRunIdIdQueryOptions(
    id,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
