/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Leekwars Tools API
 * OpenAPI spec version: 4.2.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  BrowseDirectoryRequest,
  BrowseDirectoryResponse,
} from '../leekwarsToolsAPI.schemas';

import { apiClient } from '.././lib/api-client';

/**
 * Browses into a folder from the current directory and lists its content.
 * @summary Browse into a folder
 */
export const postFileBrowseFolder = (
  browseDirectoryRequest?: BrowseDirectoryRequest,
  signal?: AbortSignal,
) => {
  return apiClient<BrowseDirectoryResponse>({
    url: `/file/browse-folder`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: browseDirectoryRequest,
    signal,
  });
};

export const getPostFileBrowseFolderMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postFileBrowseFolder>>,
    TError,
    { data: BrowseDirectoryRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postFileBrowseFolder>>,
  TError,
  { data: BrowseDirectoryRequest },
  TContext
> => {
  const mutationKey = ['postFileBrowseFolder'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postFileBrowseFolder>>,
    { data: BrowseDirectoryRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postFileBrowseFolder(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostFileBrowseFolderMutationResult = NonNullable<
  Awaited<ReturnType<typeof postFileBrowseFolder>>
>;
export type PostFileBrowseFolderMutationBody = BrowseDirectoryRequest;
export type PostFileBrowseFolderMutationError = void;

/**
 * @summary Browse into a folder
 */
export const usePostFileBrowseFolder = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postFileBrowseFolder>>,
      TError,
      { data: BrowseDirectoryRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postFileBrowseFolder>>,
  TError,
  { data: BrowseDirectoryRequest },
  TContext
> => {
  return useMutation(
    getPostFileBrowseFolderMutationOptions(options),
    queryClient,
  );
};
/**
 * Lists all files and directories in a specific directory.
 * @summary List files in a directory
 */
export const getFileListAll = (signal?: AbortSignal) => {
  return apiClient<BrowseDirectoryResponse>({
    url: `/file/list-all`,
    method: 'GET',
    signal,
  });
};

export const getGetFileListAllQueryKey = () => {
  return [`/file/list-all`] as const;
};

export const getGetFileListAllQueryOptions = <
  TData = Awaited<ReturnType<typeof getFileListAll>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getFileListAll>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetFileListAllQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getFileListAll>>> = ({
    signal,
  }) => getFileListAll(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getFileListAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetFileListAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFileListAll>>
>;
export type GetFileListAllQueryError = void;

export function useGetFileListAll<
  TData = Awaited<ReturnType<typeof getFileListAll>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFileListAll>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFileListAll>>,
          TError,
          Awaited<ReturnType<typeof getFileListAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFileListAll<
  TData = Awaited<ReturnType<typeof getFileListAll>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFileListAll>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFileListAll>>,
          TError,
          Awaited<ReturnType<typeof getFileListAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFileListAll<
  TData = Awaited<ReturnType<typeof getFileListAll>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFileListAll>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List files in a directory
 */

export function useGetFileListAll<
  TData = Awaited<ReturnType<typeof getFileListAll>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFileListAll>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetFileListAllQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Moves the current directory up one level.
 * @summary Move up one directory level
 */
export const getFileMoveUp = (signal?: AbortSignal) => {
  return apiClient<BrowseDirectoryResponse>({
    url: `/file/move-up`,
    method: 'GET',
    signal,
  });
};

export const getGetFileMoveUpQueryKey = () => {
  return [`/file/move-up`] as const;
};

export const getGetFileMoveUpQueryOptions = <
  TData = Awaited<ReturnType<typeof getFileMoveUp>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getFileMoveUp>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetFileMoveUpQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getFileMoveUp>>> = ({
    signal,
  }) => getFileMoveUp(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getFileMoveUp>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetFileMoveUpQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFileMoveUp>>
>;
export type GetFileMoveUpQueryError = void;

export function useGetFileMoveUp<
  TData = Awaited<ReturnType<typeof getFileMoveUp>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFileMoveUp>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFileMoveUp>>,
          TError,
          Awaited<ReturnType<typeof getFileMoveUp>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFileMoveUp<
  TData = Awaited<ReturnType<typeof getFileMoveUp>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFileMoveUp>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFileMoveUp>>,
          TError,
          Awaited<ReturnType<typeof getFileMoveUp>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFileMoveUp<
  TData = Awaited<ReturnType<typeof getFileMoveUp>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFileMoveUp>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Move up one directory level
 */

export function useGetFileMoveUp<
  TData = Awaited<ReturnType<typeof getFileMoveUp>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFileMoveUp>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetFileMoveUpQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Resets the current directory to the reference directory.
 * @summary Reset current directory
 */
export const getFileResetCurrentDirectory = (signal?: AbortSignal) => {
  return apiClient<BrowseDirectoryResponse>({
    url: `/file/reset-current-directory`,
    method: 'GET',
    signal,
  });
};

export const getGetFileResetCurrentDirectoryQueryKey = () => {
  return [`/file/reset-current-directory`] as const;
};

export const getGetFileResetCurrentDirectoryQueryOptions = <
  TData = Awaited<ReturnType<typeof getFileResetCurrentDirectory>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getFileResetCurrentDirectory>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetFileResetCurrentDirectoryQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getFileResetCurrentDirectory>>
  > = ({ signal }) => getFileResetCurrentDirectory(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getFileResetCurrentDirectory>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetFileResetCurrentDirectoryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFileResetCurrentDirectory>>
>;
export type GetFileResetCurrentDirectoryQueryError = void;

export function useGetFileResetCurrentDirectory<
  TData = Awaited<ReturnType<typeof getFileResetCurrentDirectory>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFileResetCurrentDirectory>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFileResetCurrentDirectory>>,
          TError,
          Awaited<ReturnType<typeof getFileResetCurrentDirectory>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFileResetCurrentDirectory<
  TData = Awaited<ReturnType<typeof getFileResetCurrentDirectory>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFileResetCurrentDirectory>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFileResetCurrentDirectory>>,
          TError,
          Awaited<ReturnType<typeof getFileResetCurrentDirectory>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFileResetCurrentDirectory<
  TData = Awaited<ReturnType<typeof getFileResetCurrentDirectory>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFileResetCurrentDirectory>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Reset current directory
 */

export function useGetFileResetCurrentDirectory<
  TData = Awaited<ReturnType<typeof getFileResetCurrentDirectory>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFileResetCurrentDirectory>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetFileResetCurrentDirectoryQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
