/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Leekwars Tools API
 * OpenAPI spec version: 4.2.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  BasePoolStopResponse,
  FarmerPoolRunResponse,
  GetAllRunningPoolsResponse,
  ListFarmerPoolRunResponse,
} from '../leekwarsToolsAPI.schemas';

import { apiClient } from '.././lib/api-client';

/**
 * Retrieves all running farmer pool runs.
 * @summary Get all running farmer pool runs
 */
export const getFarmerPoolRunAllRunning = (signal?: AbortSignal) => {
  return apiClient<GetAllRunningPoolsResponse>({
    url: `/farmer-pool-run/all-running`,
    method: 'GET',
    signal,
  });
};

export const getGetFarmerPoolRunAllRunningQueryKey = () => {
  return [`/farmer-pool-run/all-running`] as const;
};

export const getGetFarmerPoolRunAllRunningQueryOptions = <
  TData = Awaited<ReturnType<typeof getFarmerPoolRunAllRunning>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getFarmerPoolRunAllRunning>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetFarmerPoolRunAllRunningQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getFarmerPoolRunAllRunning>>
  > = ({ signal }) => getFarmerPoolRunAllRunning(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getFarmerPoolRunAllRunning>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetFarmerPoolRunAllRunningQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFarmerPoolRunAllRunning>>
>;
export type GetFarmerPoolRunAllRunningQueryError = void;

export function useGetFarmerPoolRunAllRunning<
  TData = Awaited<ReturnType<typeof getFarmerPoolRunAllRunning>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFarmerPoolRunAllRunning>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFarmerPoolRunAllRunning>>,
          TError,
          Awaited<ReturnType<typeof getFarmerPoolRunAllRunning>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFarmerPoolRunAllRunning<
  TData = Awaited<ReturnType<typeof getFarmerPoolRunAllRunning>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFarmerPoolRunAllRunning>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFarmerPoolRunAllRunning>>,
          TError,
          Awaited<ReturnType<typeof getFarmerPoolRunAllRunning>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFarmerPoolRunAllRunning<
  TData = Awaited<ReturnType<typeof getFarmerPoolRunAllRunning>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFarmerPoolRunAllRunning>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all running farmer pool runs
 */

export function useGetFarmerPoolRunAllRunning<
  TData = Awaited<ReturnType<typeof getFarmerPoolRunAllRunning>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFarmerPoolRunAllRunning>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetFarmerPoolRunAllRunningQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Gets the farmer pool runs associated with a given farmer pool ID.
 * @summary Get farmer pool runs by original pool ID
 */
export const getFarmerPoolRunGetByPoolIdId = (
  id: string,
  signal?: AbortSignal,
) => {
  return apiClient<ListFarmerPoolRunResponse>({
    url: `/farmer-pool-run/get-by-pool-id/${id}`,
    method: 'GET',
    signal,
  });
};

export const getGetFarmerPoolRunGetByPoolIdIdQueryKey = (id: string) => {
  return [`/farmer-pool-run/get-by-pool-id/${id}`] as const;
};

export const getGetFarmerPoolRunGetByPoolIdIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getFarmerPoolRunGetByPoolIdId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFarmerPoolRunGetByPoolIdId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetFarmerPoolRunGetByPoolIdIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getFarmerPoolRunGetByPoolIdId>>
  > = ({ signal }) => getFarmerPoolRunGetByPoolIdId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getFarmerPoolRunGetByPoolIdId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetFarmerPoolRunGetByPoolIdIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFarmerPoolRunGetByPoolIdId>>
>;
export type GetFarmerPoolRunGetByPoolIdIdQueryError = void;

export function useGetFarmerPoolRunGetByPoolIdId<
  TData = Awaited<ReturnType<typeof getFarmerPoolRunGetByPoolIdId>>,
  TError = void,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFarmerPoolRunGetByPoolIdId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFarmerPoolRunGetByPoolIdId>>,
          TError,
          Awaited<ReturnType<typeof getFarmerPoolRunGetByPoolIdId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFarmerPoolRunGetByPoolIdId<
  TData = Awaited<ReturnType<typeof getFarmerPoolRunGetByPoolIdId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFarmerPoolRunGetByPoolIdId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFarmerPoolRunGetByPoolIdId>>,
          TError,
          Awaited<ReturnType<typeof getFarmerPoolRunGetByPoolIdId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFarmerPoolRunGetByPoolIdId<
  TData = Awaited<ReturnType<typeof getFarmerPoolRunGetByPoolIdId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFarmerPoolRunGetByPoolIdId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get farmer pool runs by original pool ID
 */

export function useGetFarmerPoolRunGetByPoolIdId<
  TData = Awaited<ReturnType<typeof getFarmerPoolRunGetByPoolIdId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFarmerPoolRunGetByPoolIdId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetFarmerPoolRunGetByPoolIdIdQueryOptions(
    id,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Gets the farmer pool run associated with a given ID.
 * @summary Get farmer pool run by ID
 */
export const getFarmerPoolRunId = (id: string, signal?: AbortSignal) => {
  return apiClient<FarmerPoolRunResponse>({
    url: `/farmer-pool-run/${id}`,
    method: 'GET',
    signal,
  });
};

export const getGetFarmerPoolRunIdQueryKey = (id: string) => {
  return [`/farmer-pool-run/${id}`] as const;
};

export const getGetFarmerPoolRunIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getFarmerPoolRunId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFarmerPoolRunId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetFarmerPoolRunIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getFarmerPoolRunId>>
  > = ({ signal }) => getFarmerPoolRunId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getFarmerPoolRunId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetFarmerPoolRunIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFarmerPoolRunId>>
>;
export type GetFarmerPoolRunIdQueryError = void;

export function useGetFarmerPoolRunId<
  TData = Awaited<ReturnType<typeof getFarmerPoolRunId>>,
  TError = void,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFarmerPoolRunId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFarmerPoolRunId>>,
          TError,
          Awaited<ReturnType<typeof getFarmerPoolRunId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFarmerPoolRunId<
  TData = Awaited<ReturnType<typeof getFarmerPoolRunId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFarmerPoolRunId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFarmerPoolRunId>>,
          TError,
          Awaited<ReturnType<typeof getFarmerPoolRunId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFarmerPoolRunId<
  TData = Awaited<ReturnType<typeof getFarmerPoolRunId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFarmerPoolRunId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get farmer pool run by ID
 */

export function useGetFarmerPoolRunId<
  TData = Awaited<ReturnType<typeof getFarmerPoolRunId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFarmerPoolRunId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetFarmerPoolRunIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Starts a farmer pool run, which will generate fights based on the farmers in the pool and the pool's configuration.
 * @summary Start a farmer pool run
 */
export const postFarmerPoolRunIdStart = (id: string, signal?: AbortSignal) => {
  return apiClient<FarmerPoolRunResponse>({
    url: `/farmer-pool-run/${id}/start`,
    method: 'POST',
    signal,
  });
};

export const getPostFarmerPoolRunIdStartMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postFarmerPoolRunIdStart>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postFarmerPoolRunIdStart>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['postFarmerPoolRunIdStart'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postFarmerPoolRunIdStart>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return postFarmerPoolRunIdStart(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostFarmerPoolRunIdStartMutationResult = NonNullable<
  Awaited<ReturnType<typeof postFarmerPoolRunIdStart>>
>;

export type PostFarmerPoolRunIdStartMutationError = void;

/**
 * @summary Start a farmer pool run
 */
export const usePostFarmerPoolRunIdStart = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postFarmerPoolRunIdStart>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postFarmerPoolRunIdStart>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getPostFarmerPoolRunIdStartMutationOptions(options),
    queryClient,
  );
};
/**
 * Stops a farmer pool run, which will stop all ongoing fights and prevent new fights from being generated.
 * @summary Stop a farmer pool run
 */
export const postFarmerPoolRunIdStop = (id: string, signal?: AbortSignal) => {
  return apiClient<BasePoolStopResponse>({
    url: `/farmer-pool-run/${id}/stop`,
    method: 'POST',
    signal,
  });
};

export const getPostFarmerPoolRunIdStopMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postFarmerPoolRunIdStop>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postFarmerPoolRunIdStop>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['postFarmerPoolRunIdStop'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postFarmerPoolRunIdStop>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return postFarmerPoolRunIdStop(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostFarmerPoolRunIdStopMutationResult = NonNullable<
  Awaited<ReturnType<typeof postFarmerPoolRunIdStop>>
>;

export type PostFarmerPoolRunIdStopMutationError = void;

/**
 * @summary Stop a farmer pool run
 */
export const usePostFarmerPoolRunIdStop = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postFarmerPoolRunIdStop>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postFarmerPoolRunIdStop>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getPostFarmerPoolRunIdStopMutationOptions(options),
    queryClient,
  );
};
