/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Leekwars Tools API
 * OpenAPI spec version: 4.2.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import type {
  CreateTeamPoolRequest,
  TeamPoolResponse,
} from '../leekwarsToolsAPI.schemas';

import { apiClient } from '.././lib/api-client';

/**
 * Creates a new team pool.
 * @summary Create a team pool
 */
export const postTeamPoolsCreate = (
  createTeamPoolRequest: CreateTeamPoolRequest,
  signal?: AbortSignal,
) => {
  return apiClient<TeamPoolResponse>({
    url: `/team-pools/create`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createTeamPoolRequest,
    signal,
  });
};

export const getPostTeamPoolsCreateMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postTeamPoolsCreate>>,
    TError,
    { data: CreateTeamPoolRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postTeamPoolsCreate>>,
  TError,
  { data: CreateTeamPoolRequest },
  TContext
> => {
  const mutationKey = ['postTeamPoolsCreate'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postTeamPoolsCreate>>,
    { data: CreateTeamPoolRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postTeamPoolsCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostTeamPoolsCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof postTeamPoolsCreate>>
>;
export type PostTeamPoolsCreateMutationBody = CreateTeamPoolRequest;
export type PostTeamPoolsCreateMutationError = void;

/**
 * @summary Create a team pool
 */
export const usePostTeamPoolsCreate = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postTeamPoolsCreate>>,
      TError,
      { data: CreateTeamPoolRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postTeamPoolsCreate>>,
  TError,
  { data: CreateTeamPoolRequest },
  TContext
> => {
  return useMutation(
    getPostTeamPoolsCreateMutationOptions(options),
    queryClient,
  );
};
