/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Leekwars Tools API
 * OpenAPI spec version: 4.2.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  AddTurretRequest,
  GetAllTurretsResponse,
  TurretResponse,
} from '../leekwarsToolsAPI.schemas';

import { apiClient } from '.././lib/api-client';

/**
 * Adds a new turret.
 * @summary Add a new turret
 */
export const postTurretsAdd = (
  addTurretRequest?: AddTurretRequest,
  signal?: AbortSignal,
) => {
  return apiClient<TurretResponse>({
    url: `/turrets/add`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: addTurretRequest,
    signal,
  });
};

export const getPostTurretsAddMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postTurretsAdd>>,
    TError,
    { data: AddTurretRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postTurretsAdd>>,
  TError,
  { data: AddTurretRequest },
  TContext
> => {
  const mutationKey = ['postTurretsAdd'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postTurretsAdd>>,
    { data: AddTurretRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postTurretsAdd(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostTurretsAddMutationResult = NonNullable<
  Awaited<ReturnType<typeof postTurretsAdd>>
>;
export type PostTurretsAddMutationBody = AddTurretRequest;
export type PostTurretsAddMutationError = void;

/**
 * @summary Add a new turret
 */
export const usePostTurretsAdd = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postTurretsAdd>>,
      TError,
      { data: AddTurretRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postTurretsAdd>>,
  TError,
  { data: AddTurretRequest },
  TContext
> => {
  return useMutation(getPostTurretsAddMutationOptions(options), queryClient);
};
/**
 * Returns a list of all turrets.
 * @summary Get all turrets
 */
export const getTurretsAll = (signal?: AbortSignal) => {
  return apiClient<GetAllTurretsResponse>({
    url: `/turrets/all`,
    method: 'GET',
    signal,
  });
};

export const getGetTurretsAllQueryKey = () => {
  return [`/turrets/all`] as const;
};

export const getGetTurretsAllQueryOptions = <
  TData = Awaited<ReturnType<typeof getTurretsAll>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getTurretsAll>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTurretsAllQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTurretsAll>>> = ({
    signal,
  }) => getTurretsAll(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getTurretsAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetTurretsAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTurretsAll>>
>;
export type GetTurretsAllQueryError = void;

export function useGetTurretsAll<
  TData = Awaited<ReturnType<typeof getTurretsAll>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTurretsAll>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTurretsAll>>,
          TError,
          Awaited<ReturnType<typeof getTurretsAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTurretsAll<
  TData = Awaited<ReturnType<typeof getTurretsAll>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTurretsAll>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTurretsAll>>,
          TError,
          Awaited<ReturnType<typeof getTurretsAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTurretsAll<
  TData = Awaited<ReturnType<typeof getTurretsAll>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTurretsAll>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all turrets
 */

export function useGetTurretsAll<
  TData = Awaited<ReturnType<typeof getTurretsAll>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTurretsAll>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetTurretsAllQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Deletes a turret by its ID.
 * @summary Delete a turret
 */
export const deleteTurretsDeleteTurretId = (
  turretId: string,
  signal?: AbortSignal,
) => {
  return apiClient<void>({
    url: `/turrets/delete/${turretId}`,
    method: 'DELETE',
    signal,
  });
};

export const getDeleteTurretsDeleteTurretIdMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteTurretsDeleteTurretId>>,
    TError,
    { turretId: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteTurretsDeleteTurretId>>,
  TError,
  { turretId: string },
  TContext
> => {
  const mutationKey = ['deleteTurretsDeleteTurretId'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteTurretsDeleteTurretId>>,
    { turretId: string }
  > = (props) => {
    const { turretId } = props ?? {};

    return deleteTurretsDeleteTurretId(turretId);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteTurretsDeleteTurretIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteTurretsDeleteTurretId>>
>;

export type DeleteTurretsDeleteTurretIdMutationError = void;

/**
 * @summary Delete a turret
 */
export const useDeleteTurretsDeleteTurretId = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteTurretsDeleteTurretId>>,
      TError,
      { turretId: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteTurretsDeleteTurretId>>,
  TError,
  { turretId: string },
  TContext
> => {
  return useMutation(
    getDeleteTurretsDeleteTurretIdMutationOptions(options),
    queryClient,
  );
};
