/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Leekwars Tools API
 * OpenAPI spec version: 4.2.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import type {
  AddMobRequest,
  AddMobResponse,
} from '../leekwarsToolsAPI.schemas';

import { apiClient } from '.././lib/api-client';

/**
 * Adds a new mob to the system.
 * @summary Add a mob
 */
export const postMobsAdd = (
  addMobRequest: AddMobRequest,
  signal?: AbortSignal,
) => {
  return apiClient<AddMobResponse>({
    url: `/mobs/add`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: addMobRequest,
    signal,
  });
};

export const getPostMobsAddMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postMobsAdd>>,
    TError,
    { data: AddMobRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postMobsAdd>>,
  TError,
  { data: AddMobRequest },
  TContext
> => {
  const mutationKey = ['postMobsAdd'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postMobsAdd>>,
    { data: AddMobRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postMobsAdd(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostMobsAddMutationResult = NonNullable<
  Awaited<ReturnType<typeof postMobsAdd>>
>;
export type PostMobsAddMutationBody = AddMobRequest;
export type PostMobsAddMutationError = void;

/**
 * @summary Add a mob
 */
export const usePostMobsAdd = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postMobsAdd>>,
      TError,
      { data: AddMobRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postMobsAdd>>,
  TError,
  { data: AddMobRequest },
  TContext
> => {
  return useMutation(getPostMobsAddMutationOptions(options), queryClient);
};
