/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Leekwars Tools API
 * OpenAPI spec version: 4.2.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import type {
  CreatePumpkinPoolRequest,
  PumpkinPoolResponse,
} from '../leekwarsToolsAPI.schemas';

import { apiClient } from '.././lib/api-client';

/**
 * Creates a new pumpkin pool.
 * @summary Create a pumpkin pool
 */
export const postPumpkinPoolsCreate = (
  createPumpkinPoolRequest: CreatePumpkinPoolRequest,
  signal?: AbortSignal,
) => {
  return apiClient<PumpkinPoolResponse>({
    url: `/pumpkin-pools/create`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createPumpkinPoolRequest,
    signal,
  });
};

export const getPostPumpkinPoolsCreateMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postPumpkinPoolsCreate>>,
    TError,
    { data: CreatePumpkinPoolRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postPumpkinPoolsCreate>>,
  TError,
  { data: CreatePumpkinPoolRequest },
  TContext
> => {
  const mutationKey = ['postPumpkinPoolsCreate'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postPumpkinPoolsCreate>>,
    { data: CreatePumpkinPoolRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postPumpkinPoolsCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostPumpkinPoolsCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof postPumpkinPoolsCreate>>
>;
export type PostPumpkinPoolsCreateMutationBody = CreatePumpkinPoolRequest;
export type PostPumpkinPoolsCreateMutationError = void;

/**
 * @summary Create a pumpkin pool
 */
export const usePostPumpkinPoolsCreate = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postPumpkinPoolsCreate>>,
      TError,
      { data: CreatePumpkinPoolRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postPumpkinPoolsCreate>>,
  TError,
  { data: CreatePumpkinPoolRequest },
  TContext
> => {
  return useMutation(
    getPostPumpkinPoolsCreateMutationOptions(options),
    queryClient,
  );
};
