/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Leekwars Tools API
 * OpenAPI spec version: 4.2.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  BasePoolResponse,
  GetBasePoolsResponse,
  SetBooleanRequest,
  SetIntegerRequest,
  UpdatePoolNameRequest,
} from '../leekwarsToolsAPI.schemas';

import { apiClient } from '.././lib/api-client';

/**
 * Returns a list of all base pools.
 * @summary Get all base pools
 */
export const getBasePoolsAll = (signal?: AbortSignal) => {
  return apiClient<GetBasePoolsResponse>({
    url: `/base-pools/all`,
    method: 'GET',
    signal,
  });
};

export const getGetBasePoolsAllQueryKey = () => {
  return [`/base-pools/all`] as const;
};

export const getGetBasePoolsAllQueryOptions = <
  TData = Awaited<ReturnType<typeof getBasePoolsAll>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getBasePoolsAll>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetBasePoolsAllQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getBasePoolsAll>>> = ({
    signal,
  }) => getBasePoolsAll(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getBasePoolsAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetBasePoolsAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof getBasePoolsAll>>
>;
export type GetBasePoolsAllQueryError = void;

export function useGetBasePoolsAll<
  TData = Awaited<ReturnType<typeof getBasePoolsAll>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBasePoolsAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBasePoolsAll>>,
          TError,
          Awaited<ReturnType<typeof getBasePoolsAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBasePoolsAll<
  TData = Awaited<ReturnType<typeof getBasePoolsAll>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBasePoolsAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBasePoolsAll>>,
          TError,
          Awaited<ReturnType<typeof getBasePoolsAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBasePoolsAll<
  TData = Awaited<ReturnType<typeof getBasePoolsAll>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBasePoolsAll>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all base pools
 */

export function useGetBasePoolsAll<
  TData = Awaited<ReturnType<typeof getBasePoolsAll>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBasePoolsAll>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetBasePoolsAllQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Sets the deterministic property of a base pool by its ID.
 * @summary Set deterministic for a base pool
 */
export const postBasePoolsIdSetDeterministic = (
  id: string,
  setBooleanRequest: SetBooleanRequest,
  signal?: AbortSignal,
) => {
  return apiClient<BasePoolResponse>({
    url: `/base-pools/${id}/set-deterministic`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: setBooleanRequest,
    signal,
  });
};

export const getPostBasePoolsIdSetDeterministicMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postBasePoolsIdSetDeterministic>>,
    TError,
    { id: string; data: SetBooleanRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postBasePoolsIdSetDeterministic>>,
  TError,
  { id: string; data: SetBooleanRequest },
  TContext
> => {
  const mutationKey = ['postBasePoolsIdSetDeterministic'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postBasePoolsIdSetDeterministic>>,
    { id: string; data: SetBooleanRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return postBasePoolsIdSetDeterministic(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostBasePoolsIdSetDeterministicMutationResult = NonNullable<
  Awaited<ReturnType<typeof postBasePoolsIdSetDeterministic>>
>;
export type PostBasePoolsIdSetDeterministicMutationBody = SetBooleanRequest;
export type PostBasePoolsIdSetDeterministicMutationError = void;

/**
 * @summary Set deterministic for a base pool
 */
export const usePostBasePoolsIdSetDeterministic = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postBasePoolsIdSetDeterministic>>,
      TError,
      { id: string; data: SetBooleanRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postBasePoolsIdSetDeterministic>>,
  TError,
  { id: string; data: SetBooleanRequest },
  TContext
> => {
  return useMutation(
    getPostBasePoolsIdSetDeterministicMutationOptions(options),
    queryClient,
  );
};
/**
 * Enables or disables a base pool by its ID.
 * @summary Enable or disable a base pool
 */
export const postBasePoolsIdSetEnabled = (
  id: string,
  setBooleanRequest: SetBooleanRequest,
  signal?: AbortSignal,
) => {
  return apiClient<BasePoolResponse>({
    url: `/base-pools/${id}/set-enabled`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: setBooleanRequest,
    signal,
  });
};

export const getPostBasePoolsIdSetEnabledMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postBasePoolsIdSetEnabled>>,
    TError,
    { id: string; data: SetBooleanRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postBasePoolsIdSetEnabled>>,
  TError,
  { id: string; data: SetBooleanRequest },
  TContext
> => {
  const mutationKey = ['postBasePoolsIdSetEnabled'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postBasePoolsIdSetEnabled>>,
    { id: string; data: SetBooleanRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return postBasePoolsIdSetEnabled(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostBasePoolsIdSetEnabledMutationResult = NonNullable<
  Awaited<ReturnType<typeof postBasePoolsIdSetEnabled>>
>;
export type PostBasePoolsIdSetEnabledMutationBody = SetBooleanRequest;
export type PostBasePoolsIdSetEnabledMutationError = void;

/**
 * @summary Enable or disable a base pool
 */
export const usePostBasePoolsIdSetEnabled = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postBasePoolsIdSetEnabled>>,
      TError,
      { id: string; data: SetBooleanRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postBasePoolsIdSetEnabled>>,
  TError,
  { id: string; data: SetBooleanRequest },
  TContext
> => {
  return useMutation(
    getPostBasePoolsIdSetEnabledMutationOptions(options),
    queryClient,
  );
};
/**
 * Sets the fightLimit property of a base pool by its ID.
 * @summary Set fight limit for a base pool
 */
export const postBasePoolsIdSetFightLimit = (
  id: string,
  setIntegerRequest: SetIntegerRequest,
  signal?: AbortSignal,
) => {
  return apiClient<BasePoolResponse>({
    url: `/base-pools/${id}/set-fight-limit`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: setIntegerRequest,
    signal,
  });
};

export const getPostBasePoolsIdSetFightLimitMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postBasePoolsIdSetFightLimit>>,
    TError,
    { id: string; data: SetIntegerRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postBasePoolsIdSetFightLimit>>,
  TError,
  { id: string; data: SetIntegerRequest },
  TContext
> => {
  const mutationKey = ['postBasePoolsIdSetFightLimit'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postBasePoolsIdSetFightLimit>>,
    { id: string; data: SetIntegerRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return postBasePoolsIdSetFightLimit(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostBasePoolsIdSetFightLimitMutationResult = NonNullable<
  Awaited<ReturnType<typeof postBasePoolsIdSetFightLimit>>
>;
export type PostBasePoolsIdSetFightLimitMutationBody = SetIntegerRequest;
export type PostBasePoolsIdSetFightLimitMutationError = void;

/**
 * @summary Set fight limit for a base pool
 */
export const usePostBasePoolsIdSetFightLimit = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postBasePoolsIdSetFightLimit>>,
      TError,
      { id: string; data: SetIntegerRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postBasePoolsIdSetFightLimit>>,
  TError,
  { id: string; data: SetIntegerRequest },
  TContext
> => {
  return useMutation(
    getPostBasePoolsIdSetFightLimitMutationOptions(options),
    queryClient,
  );
};
/**
 * Enables or disables the fight limit for a base pool by its ID.
 * @summary Enable or disable fight limit for a base pool
 */
export const postBasePoolsIdSetFightLimitEnabled = (
  id: string,
  setBooleanRequest: SetBooleanRequest,
  signal?: AbortSignal,
) => {
  return apiClient<BasePoolResponse>({
    url: `/base-pools/${id}/set-fight-limit-enabled`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: setBooleanRequest,
    signal,
  });
};

export const getPostBasePoolsIdSetFightLimitEnabledMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postBasePoolsIdSetFightLimitEnabled>>,
    TError,
    { id: string; data: SetBooleanRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postBasePoolsIdSetFightLimitEnabled>>,
  TError,
  { id: string; data: SetBooleanRequest },
  TContext
> => {
  const mutationKey = ['postBasePoolsIdSetFightLimitEnabled'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postBasePoolsIdSetFightLimitEnabled>>,
    { id: string; data: SetBooleanRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return postBasePoolsIdSetFightLimitEnabled(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostBasePoolsIdSetFightLimitEnabledMutationResult = NonNullable<
  Awaited<ReturnType<typeof postBasePoolsIdSetFightLimitEnabled>>
>;
export type PostBasePoolsIdSetFightLimitEnabledMutationBody = SetBooleanRequest;
export type PostBasePoolsIdSetFightLimitEnabledMutationError = void;

/**
 * @summary Enable or disable fight limit for a base pool
 */
export const usePostBasePoolsIdSetFightLimitEnabled = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postBasePoolsIdSetFightLimitEnabled>>,
      TError,
      { id: string; data: SetBooleanRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postBasePoolsIdSetFightLimitEnabled>>,
  TError,
  { id: string; data: SetBooleanRequest },
  TContext
> => {
  return useMutation(
    getPostBasePoolsIdSetFightLimitEnabledMutationOptions(options),
    queryClient,
  );
};
/**
 * Sets the name of a base pool by its ID.
 * @summary Set name for a base pool
 */
export const postBasePoolsIdSetName = (
  id: string,
  updatePoolNameRequest: UpdatePoolNameRequest,
  signal?: AbortSignal,
) => {
  return apiClient<BasePoolResponse>({
    url: `/base-pools/${id}/set-name`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: updatePoolNameRequest,
    signal,
  });
};

export const getPostBasePoolsIdSetNameMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postBasePoolsIdSetName>>,
    TError,
    { id: string; data: UpdatePoolNameRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postBasePoolsIdSetName>>,
  TError,
  { id: string; data: UpdatePoolNameRequest },
  TContext
> => {
  const mutationKey = ['postBasePoolsIdSetName'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postBasePoolsIdSetName>>,
    { id: string; data: UpdatePoolNameRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return postBasePoolsIdSetName(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostBasePoolsIdSetNameMutationResult = NonNullable<
  Awaited<ReturnType<typeof postBasePoolsIdSetName>>
>;
export type PostBasePoolsIdSetNameMutationBody = UpdatePoolNameRequest;
export type PostBasePoolsIdSetNameMutationError = void;

/**
 * @summary Set name for a base pool
 */
export const usePostBasePoolsIdSetName = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postBasePoolsIdSetName>>,
      TError,
      { id: string; data: UpdatePoolNameRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postBasePoolsIdSetName>>,
  TError,
  { id: string; data: UpdatePoolNameRequest },
  TContext
> => {
  return useMutation(
    getPostBasePoolsIdSetNameMutationOptions(options),
    queryClient,
  );
};
/**
 * Sets the resetElo property of a base pool by its ID.
 * @summary Set resetElo for a base pool
 */
export const postBasePoolsIdSetResetElo = (
  id: string,
  setBooleanRequest: SetBooleanRequest,
  signal?: AbortSignal,
) => {
  return apiClient<BasePoolResponse>({
    url: `/base-pools/${id}/set-reset-elo`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: setBooleanRequest,
    signal,
  });
};

export const getPostBasePoolsIdSetResetEloMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postBasePoolsIdSetResetElo>>,
    TError,
    { id: string; data: SetBooleanRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postBasePoolsIdSetResetElo>>,
  TError,
  { id: string; data: SetBooleanRequest },
  TContext
> => {
  const mutationKey = ['postBasePoolsIdSetResetElo'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postBasePoolsIdSetResetElo>>,
    { id: string; data: SetBooleanRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return postBasePoolsIdSetResetElo(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostBasePoolsIdSetResetEloMutationResult = NonNullable<
  Awaited<ReturnType<typeof postBasePoolsIdSetResetElo>>
>;
export type PostBasePoolsIdSetResetEloMutationBody = SetBooleanRequest;
export type PostBasePoolsIdSetResetEloMutationError = void;

/**
 * @summary Set resetElo for a base pool
 */
export const usePostBasePoolsIdSetResetElo = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postBasePoolsIdSetResetElo>>,
      TError,
      { id: string; data: SetBooleanRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postBasePoolsIdSetResetElo>>,
  TError,
  { id: string; data: SetBooleanRequest },
  TContext
> => {
  return useMutation(
    getPostBasePoolsIdSetResetEloMutationOptions(options),
    queryClient,
  );
};
/**
 * Sets the startSeed property of a base pool by its ID.
 * @summary Set start seed for a base pool
 */
export const postBasePoolsIdSetStartSeed = (
  id: string,
  setIntegerRequest: SetIntegerRequest,
  signal?: AbortSignal,
) => {
  return apiClient<BasePoolResponse>({
    url: `/base-pools/${id}/set-start-seed`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: setIntegerRequest,
    signal,
  });
};

export const getPostBasePoolsIdSetStartSeedMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postBasePoolsIdSetStartSeed>>,
    TError,
    { id: string; data: SetIntegerRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postBasePoolsIdSetStartSeed>>,
  TError,
  { id: string; data: SetIntegerRequest },
  TContext
> => {
  const mutationKey = ['postBasePoolsIdSetStartSeed'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postBasePoolsIdSetStartSeed>>,
    { id: string; data: SetIntegerRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return postBasePoolsIdSetStartSeed(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostBasePoolsIdSetStartSeedMutationResult = NonNullable<
  Awaited<ReturnType<typeof postBasePoolsIdSetStartSeed>>
>;
export type PostBasePoolsIdSetStartSeedMutationBody = SetIntegerRequest;
export type PostBasePoolsIdSetStartSeedMutationError = void;

/**
 * @summary Set start seed for a base pool
 */
export const usePostBasePoolsIdSetStartSeed = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postBasePoolsIdSetStartSeed>>,
      TError,
      { id: string; data: SetIntegerRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postBasePoolsIdSetStartSeed>>,
  TError,
  { id: string; data: SetIntegerRequest },
  TContext
> => {
  return useMutation(
    getPostBasePoolsIdSetStartSeedMutationOptions(options),
    queryClient,
  );
};
