/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Leekwars Tools API
 * OpenAPI spec version: 4.2.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  ListPumpkinPoolRunResponse,
  PumpkinPoolRunResponse,
} from '../leekwarsToolsAPI.schemas';

import { apiClient } from '.././lib/api-client';

/**
 * Gets the pumpkin pool runs associated with a given pumpkin pool ID.
 * @summary Get pumpkin pool runs by original pool ID
 */
export const getPumpkinPoolRunGetByPoolIdId = (
  id: string,
  signal?: AbortSignal,
) => {
  return apiClient<ListPumpkinPoolRunResponse>({
    url: `/pumpkin-pool-run/get-by-pool-id/${id}`,
    method: 'GET',
    signal,
  });
};

export const getGetPumpkinPoolRunGetByPoolIdIdQueryKey = (id: string) => {
  return [`/pumpkin-pool-run/get-by-pool-id/${id}`] as const;
};

export const getGetPumpkinPoolRunGetByPoolIdIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getPumpkinPoolRunGetByPoolIdId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPumpkinPoolRunGetByPoolIdId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetPumpkinPoolRunGetByPoolIdIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getPumpkinPoolRunGetByPoolIdId>>
  > = ({ signal }) => getPumpkinPoolRunGetByPoolIdId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getPumpkinPoolRunGetByPoolIdId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPumpkinPoolRunGetByPoolIdIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPumpkinPoolRunGetByPoolIdId>>
>;
export type GetPumpkinPoolRunGetByPoolIdIdQueryError = void;

export function useGetPumpkinPoolRunGetByPoolIdId<
  TData = Awaited<ReturnType<typeof getPumpkinPoolRunGetByPoolIdId>>,
  TError = void,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPumpkinPoolRunGetByPoolIdId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPumpkinPoolRunGetByPoolIdId>>,
          TError,
          Awaited<ReturnType<typeof getPumpkinPoolRunGetByPoolIdId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPumpkinPoolRunGetByPoolIdId<
  TData = Awaited<ReturnType<typeof getPumpkinPoolRunGetByPoolIdId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPumpkinPoolRunGetByPoolIdId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPumpkinPoolRunGetByPoolIdId>>,
          TError,
          Awaited<ReturnType<typeof getPumpkinPoolRunGetByPoolIdId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPumpkinPoolRunGetByPoolIdId<
  TData = Awaited<ReturnType<typeof getPumpkinPoolRunGetByPoolIdId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPumpkinPoolRunGetByPoolIdId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get pumpkin pool runs by original pool ID
 */

export function useGetPumpkinPoolRunGetByPoolIdId<
  TData = Awaited<ReturnType<typeof getPumpkinPoolRunGetByPoolIdId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPumpkinPoolRunGetByPoolIdId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPumpkinPoolRunGetByPoolIdIdQueryOptions(
    id,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Gets the pumpkin pool run associated with a given ID.
 * @summary Get pumpkin pool run by ID
 */
export const getPumpkinPoolRunId = (id: string, signal?: AbortSignal) => {
  return apiClient<PumpkinPoolRunResponse>({
    url: `/pumpkin-pool-run/${id}`,
    method: 'GET',
    signal,
  });
};

export const getGetPumpkinPoolRunIdQueryKey = (id: string) => {
  return [`/pumpkin-pool-run/${id}`] as const;
};

export const getGetPumpkinPoolRunIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getPumpkinPoolRunId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPumpkinPoolRunId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPumpkinPoolRunIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getPumpkinPoolRunId>>
  > = ({ signal }) => getPumpkinPoolRunId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getPumpkinPoolRunId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPumpkinPoolRunIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPumpkinPoolRunId>>
>;
export type GetPumpkinPoolRunIdQueryError = void;

export function useGetPumpkinPoolRunId<
  TData = Awaited<ReturnType<typeof getPumpkinPoolRunId>>,
  TError = void,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPumpkinPoolRunId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPumpkinPoolRunId>>,
          TError,
          Awaited<ReturnType<typeof getPumpkinPoolRunId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPumpkinPoolRunId<
  TData = Awaited<ReturnType<typeof getPumpkinPoolRunId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPumpkinPoolRunId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPumpkinPoolRunId>>,
          TError,
          Awaited<ReturnType<typeof getPumpkinPoolRunId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPumpkinPoolRunId<
  TData = Awaited<ReturnType<typeof getPumpkinPoolRunId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPumpkinPoolRunId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get pumpkin pool run by ID
 */

export function useGetPumpkinPoolRunId<
  TData = Awaited<ReturnType<typeof getPumpkinPoolRunId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPumpkinPoolRunId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPumpkinPoolRunIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Starts a pumpkin pool run, which will generate fights based on the farmers in the pool and the pool's configuration.
 * @summary Start a pumpkin pool run
 */
export const postPumpkinPoolRunIdStart = (id: string, signal?: AbortSignal) => {
  return apiClient<PumpkinPoolRunResponse>({
    url: `/pumpkin-pool-run/${id}/start`,
    method: 'POST',
    signal,
  });
};

export const getPostPumpkinPoolRunIdStartMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postPumpkinPoolRunIdStart>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postPumpkinPoolRunIdStart>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['postPumpkinPoolRunIdStart'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postPumpkinPoolRunIdStart>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return postPumpkinPoolRunIdStart(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostPumpkinPoolRunIdStartMutationResult = NonNullable<
  Awaited<ReturnType<typeof postPumpkinPoolRunIdStart>>
>;

export type PostPumpkinPoolRunIdStartMutationError = void;

/**
 * @summary Start a pumpkin pool run
 */
export const usePostPumpkinPoolRunIdStart = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postPumpkinPoolRunIdStart>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postPumpkinPoolRunIdStart>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getPostPumpkinPoolRunIdStartMutationOptions(options),
    queryClient,
  );
};
/**
 * Stops a running pumpkin pool run.
 * @summary Stop a pumpkin pool run
 */
export const postPumpkinPoolRunIdStop = (id: string, signal?: AbortSignal) => {
  return apiClient<void>({
    url: `/pumpkin-pool-run/${id}/stop`,
    method: 'POST',
    signal,
  });
};

export const getPostPumpkinPoolRunIdStopMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postPumpkinPoolRunIdStop>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postPumpkinPoolRunIdStop>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['postPumpkinPoolRunIdStop'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postPumpkinPoolRunIdStop>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return postPumpkinPoolRunIdStop(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostPumpkinPoolRunIdStopMutationResult = NonNullable<
  Awaited<ReturnType<typeof postPumpkinPoolRunIdStop>>
>;

export type PostPumpkinPoolRunIdStopMutationError = void;

/**
 * @summary Stop a pumpkin pool run
 */
export const usePostPumpkinPoolRunIdStop = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postPumpkinPoolRunIdStop>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postPumpkinPoolRunIdStop>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getPostPumpkinPoolRunIdStopMutationOptions(options),
    queryClient,
  );
};
