/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Leekwars Tools API
 * OpenAPI spec version: 4.2.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  AddLeekRequest,
  AddLeekResponse,
  GetAllLeeksResponse,
} from '../leekwarsToolsAPI.schemas';

import { apiClient } from '.././lib/api-client';

/**
 * Adds a new leek to the system.
 * @summary Add a leek
 */
export const postLeeksAdd = (
  addLeekRequest: AddLeekRequest,
  signal?: AbortSignal,
) => {
  return apiClient<AddLeekResponse>({
    url: `/leeks/add`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: addLeekRequest,
    signal,
  });
};

export const getPostLeeksAddMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postLeeksAdd>>,
    TError,
    { data: AddLeekRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postLeeksAdd>>,
  TError,
  { data: AddLeekRequest },
  TContext
> => {
  const mutationKey = ['postLeeksAdd'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postLeeksAdd>>,
    { data: AddLeekRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postLeeksAdd(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostLeeksAddMutationResult = NonNullable<
  Awaited<ReturnType<typeof postLeeksAdd>>
>;
export type PostLeeksAddMutationBody = AddLeekRequest;
export type PostLeeksAddMutationError = void;

/**
 * @summary Add a leek
 */
export const usePostLeeksAdd = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postLeeksAdd>>,
      TError,
      { data: AddLeekRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postLeeksAdd>>,
  TError,
  { data: AddLeekRequest },
  TContext
> => {
  return useMutation(getPostLeeksAddMutationOptions(options), queryClient);
};
/**
 * Returns a list of all leeks.
 * @summary Get all leeks
 */
export const getLeeksAll = (signal?: AbortSignal) => {
  return apiClient<GetAllLeeksResponse>({
    url: `/leeks/all`,
    method: 'GET',
    signal,
  });
};

export const getGetLeeksAllQueryKey = () => {
  return [`/leeks/all`] as const;
};

export const getGetLeeksAllQueryOptions = <
  TData = Awaited<ReturnType<typeof getLeeksAll>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getLeeksAll>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetLeeksAllQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getLeeksAll>>> = ({
    signal,
  }) => getLeeksAll(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getLeeksAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetLeeksAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof getLeeksAll>>
>;
export type GetLeeksAllQueryError = void;

export function useGetLeeksAll<
  TData = Awaited<ReturnType<typeof getLeeksAll>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getLeeksAll>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLeeksAll>>,
          TError,
          Awaited<ReturnType<typeof getLeeksAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetLeeksAll<
  TData = Awaited<ReturnType<typeof getLeeksAll>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getLeeksAll>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLeeksAll>>,
          TError,
          Awaited<ReturnType<typeof getLeeksAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetLeeksAll<
  TData = Awaited<ReturnType<typeof getLeeksAll>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getLeeksAll>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all leeks
 */

export function useGetLeeksAll<
  TData = Awaited<ReturnType<typeof getLeeksAll>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getLeeksAll>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetLeeksAllQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
