/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Leekwars Tools API
 * OpenAPI spec version: 4.2.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  GenerateFightRequest,
  GenerateFightResponse,
  GetCountByPoolRunIdResponse,
  GetPumpkinFightsByPoolRunIdResponse,
} from '../leekwarsToolsAPI.schemas';

import { apiClient } from '.././lib/api-client';

/**
 * Generates a fight based on the provided fight ID. The fight ID should correspond to an existing fight in the system.
 * @summary Generate a fight
 */
export const postFightPumpkinGenerate = (
  generateFightRequest: GenerateFightRequest,
  signal?: AbortSignal,
) => {
  return apiClient<GenerateFightResponse>({
    url: `/fight/pumpkin/generate`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: generateFightRequest,
    signal,
  });
};

export const getPostFightPumpkinGenerateMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postFightPumpkinGenerate>>,
    TError,
    { data: GenerateFightRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postFightPumpkinGenerate>>,
  TError,
  { data: GenerateFightRequest },
  TContext
> => {
  const mutationKey = ['postFightPumpkinGenerate'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postFightPumpkinGenerate>>,
    { data: GenerateFightRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postFightPumpkinGenerate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostFightPumpkinGenerateMutationResult = NonNullable<
  Awaited<ReturnType<typeof postFightPumpkinGenerate>>
>;
export type PostFightPumpkinGenerateMutationBody = GenerateFightRequest;
export type PostFightPumpkinGenerateMutationError = void;

/**
 * @summary Generate a fight
 */
export const usePostFightPumpkinGenerate = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postFightPumpkinGenerate>>,
      TError,
      { data: GenerateFightRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postFightPumpkinGenerate>>,
  TError,
  { data: GenerateFightRequest },
  TContext
> => {
  return useMutation(
    getPostFightPumpkinGenerateMutationOptions(options),
    queryClient,
  );
};
/**
 * Retrieves a list of fights associated with a specific pool run ID.
 * @summary Get fights by pool run ID
 */
export const getFightPumpkinGetByPoolRunIdIdOffsetLimit = (
  id: string,
  offset: string,
  limit: string,
  signal?: AbortSignal,
) => {
  return apiClient<GetPumpkinFightsByPoolRunIdResponse>({
    url: `/fight/pumpkin/get-by-pool-run-id/${id}/${offset}/${limit}`,
    method: 'GET',
    signal,
  });
};

export const getGetFightPumpkinGetByPoolRunIdIdOffsetLimitQueryKey = (
  id: string,
  offset: string,
  limit: string,
) => {
  return [
    `/fight/pumpkin/get-by-pool-run-id/${id}/${offset}/${limit}`,
  ] as const;
};

export const getGetFightPumpkinGetByPoolRunIdIdOffsetLimitQueryOptions = <
  TData = Awaited<
    ReturnType<typeof getFightPumpkinGetByPoolRunIdIdOffsetLimit>
  >,
  TError = void,
>(
  id: string,
  offset: string,
  limit: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightPumpkinGetByPoolRunIdIdOffsetLimit>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetFightPumpkinGetByPoolRunIdIdOffsetLimitQueryKey(id, offset, limit);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getFightPumpkinGetByPoolRunIdIdOffsetLimit>>
  > = ({ signal }) =>
    getFightPumpkinGetByPoolRunIdIdOffsetLimit(id, offset, limit, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(id && offset && limit),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getFightPumpkinGetByPoolRunIdIdOffsetLimit>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetFightPumpkinGetByPoolRunIdIdOffsetLimitQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFightPumpkinGetByPoolRunIdIdOffsetLimit>>
>;
export type GetFightPumpkinGetByPoolRunIdIdOffsetLimitQueryError = void;

export function useGetFightPumpkinGetByPoolRunIdIdOffsetLimit<
  TData = Awaited<
    ReturnType<typeof getFightPumpkinGetByPoolRunIdIdOffsetLimit>
  >,
  TError = void,
>(
  id: string,
  offset: string,
  limit: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightPumpkinGetByPoolRunIdIdOffsetLimit>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof getFightPumpkinGetByPoolRunIdIdOffsetLimit>
          >,
          TError,
          Awaited<ReturnType<typeof getFightPumpkinGetByPoolRunIdIdOffsetLimit>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFightPumpkinGetByPoolRunIdIdOffsetLimit<
  TData = Awaited<
    ReturnType<typeof getFightPumpkinGetByPoolRunIdIdOffsetLimit>
  >,
  TError = void,
>(
  id: string,
  offset: string,
  limit: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightPumpkinGetByPoolRunIdIdOffsetLimit>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof getFightPumpkinGetByPoolRunIdIdOffsetLimit>
          >,
          TError,
          Awaited<ReturnType<typeof getFightPumpkinGetByPoolRunIdIdOffsetLimit>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFightPumpkinGetByPoolRunIdIdOffsetLimit<
  TData = Awaited<
    ReturnType<typeof getFightPumpkinGetByPoolRunIdIdOffsetLimit>
  >,
  TError = void,
>(
  id: string,
  offset: string,
  limit: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightPumpkinGetByPoolRunIdIdOffsetLimit>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get fights by pool run ID
 */

export function useGetFightPumpkinGetByPoolRunIdIdOffsetLimit<
  TData = Awaited<
    ReturnType<typeof getFightPumpkinGetByPoolRunIdIdOffsetLimit>
  >,
  TError = void,
>(
  id: string,
  offset: string,
  limit: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightPumpkinGetByPoolRunIdIdOffsetLimit>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getGetFightPumpkinGetByPoolRunIdIdOffsetLimitQueryOptions(
      id,
      offset,
      limit,
      options,
    );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Retrieves the count of fights associated with a specific pool run ID.
 * @summary Get fight count by pool run ID
 */
export const getFightPumpkinGetCountByPoolRunIdId = (
  id: string,
  signal?: AbortSignal,
) => {
  return apiClient<GetCountByPoolRunIdResponse>({
    url: `/fight/pumpkin/get-count-by-pool-run-id/${id}`,
    method: 'GET',
    signal,
  });
};

export const getGetFightPumpkinGetCountByPoolRunIdIdQueryKey = (id: string) => {
  return [`/fight/pumpkin/get-count-by-pool-run-id/${id}`] as const;
};

export const getGetFightPumpkinGetCountByPoolRunIdIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getFightPumpkinGetCountByPoolRunIdId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightPumpkinGetCountByPoolRunIdId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetFightPumpkinGetCountByPoolRunIdIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getFightPumpkinGetCountByPoolRunIdId>>
  > = ({ signal }) => getFightPumpkinGetCountByPoolRunIdId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getFightPumpkinGetCountByPoolRunIdId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetFightPumpkinGetCountByPoolRunIdIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFightPumpkinGetCountByPoolRunIdId>>
>;
export type GetFightPumpkinGetCountByPoolRunIdIdQueryError = void;

export function useGetFightPumpkinGetCountByPoolRunIdId<
  TData = Awaited<ReturnType<typeof getFightPumpkinGetCountByPoolRunIdId>>,
  TError = void,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightPumpkinGetCountByPoolRunIdId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFightPumpkinGetCountByPoolRunIdId>>,
          TError,
          Awaited<ReturnType<typeof getFightPumpkinGetCountByPoolRunIdId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFightPumpkinGetCountByPoolRunIdId<
  TData = Awaited<ReturnType<typeof getFightPumpkinGetCountByPoolRunIdId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightPumpkinGetCountByPoolRunIdId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFightPumpkinGetCountByPoolRunIdId>>,
          TError,
          Awaited<ReturnType<typeof getFightPumpkinGetCountByPoolRunIdId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFightPumpkinGetCountByPoolRunIdId<
  TData = Awaited<ReturnType<typeof getFightPumpkinGetCountByPoolRunIdId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightPumpkinGetCountByPoolRunIdId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get fight count by pool run ID
 */

export function useGetFightPumpkinGetCountByPoolRunIdId<
  TData = Awaited<ReturnType<typeof getFightPumpkinGetCountByPoolRunIdId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFightPumpkinGetCountByPoolRunIdId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetFightPumpkinGetCountByPoolRunIdIdQueryOptions(
    id,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
