/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Leekwars Tools API
 * OpenAPI spec version: 4.2.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { apiClient } from '.././lib/api-client';

/**
 * Retrieves the logs for a specific fight based on the provided fight ID.
 * @summary Get fight logs
 */
export const getApiFightGetLogsId = (id: string, signal?: AbortSignal) => {
  return apiClient<void>({
    url: `/api/fight/get-logs/${id}`,
    method: 'GET',
    signal,
  });
};

export const getGetApiFightGetLogsIdQueryKey = (id: string) => {
  return [`/api/fight/get-logs/${id}`] as const;
};

export const getGetApiFightGetLogsIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiFightGetLogsId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiFightGetLogsId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiFightGetLogsIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiFightGetLogsId>>
  > = ({ signal }) => getApiFightGetLogsId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiFightGetLogsId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiFightGetLogsIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiFightGetLogsId>>
>;
export type GetApiFightGetLogsIdQueryError = void;

export function useGetApiFightGetLogsId<
  TData = Awaited<ReturnType<typeof getApiFightGetLogsId>>,
  TError = void,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiFightGetLogsId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiFightGetLogsId>>,
          TError,
          Awaited<ReturnType<typeof getApiFightGetLogsId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiFightGetLogsId<
  TData = Awaited<ReturnType<typeof getApiFightGetLogsId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiFightGetLogsId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiFightGetLogsId>>,
          TError,
          Awaited<ReturnType<typeof getApiFightGetLogsId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiFightGetLogsId<
  TData = Awaited<ReturnType<typeof getApiFightGetLogsId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiFightGetLogsId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get fight logs
 */

export function useGetApiFightGetLogsId<
  TData = Awaited<ReturnType<typeof getApiFightGetLogsId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiFightGetLogsId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiFightGetLogsIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Retrieves the data for a specific fight based on the provided fight ID.
 * @summary Get fight data
 */
export const getApiFightGetId = (id: string, signal?: AbortSignal) => {
  return apiClient<void>({
    url: `/api/fight/get/${id}`,
    method: 'GET',
    signal,
  });
};

export const getGetApiFightGetIdQueryKey = (id: string) => {
  return [`/api/fight/get/${id}`] as const;
};

export const getGetApiFightGetIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiFightGetId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiFightGetId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiFightGetIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiFightGetId>>
  > = ({ signal }) => getApiFightGetId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiFightGetId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiFightGetIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiFightGetId>>
>;
export type GetApiFightGetIdQueryError = void;

export function useGetApiFightGetId<
  TData = Awaited<ReturnType<typeof getApiFightGetId>>,
  TError = void,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiFightGetId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiFightGetId>>,
          TError,
          Awaited<ReturnType<typeof getApiFightGetId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiFightGetId<
  TData = Awaited<ReturnType<typeof getApiFightGetId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiFightGetId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiFightGetId>>,
          TError,
          Awaited<ReturnType<typeof getApiFightGetId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiFightGetId<
  TData = Awaited<ReturnType<typeof getApiFightGetId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiFightGetId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get fight data
 */

export function useGetApiFightGetId<
  TData = Awaited<ReturnType<typeof getApiFightGetId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiFightGetId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiFightGetIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
