/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Leekwars Tools API
 * OpenAPI spec version: 4.2.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { GetBasePoolsResponse } from '../leekwarsToolsAPI.schemas';

import { apiClient } from '.././lib/api-client';

/**
 * Returns a list of all base pools.
 * @summary Get all base pools
 */
export const getBasePoolsAll = (signal?: AbortSignal) => {
  return apiClient<GetBasePoolsResponse>({
    url: `/base-pools/all`,
    method: 'GET',
    signal,
  });
};

export const getGetBasePoolsAllQueryKey = () => {
  return [`/base-pools/all`] as const;
};

export const getGetBasePoolsAllQueryOptions = <
  TData = Awaited<ReturnType<typeof getBasePoolsAll>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getBasePoolsAll>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetBasePoolsAllQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getBasePoolsAll>>> = ({
    signal,
  }) => getBasePoolsAll(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getBasePoolsAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetBasePoolsAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof getBasePoolsAll>>
>;
export type GetBasePoolsAllQueryError = void;

export function useGetBasePoolsAll<
  TData = Awaited<ReturnType<typeof getBasePoolsAll>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBasePoolsAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBasePoolsAll>>,
          TError,
          Awaited<ReturnType<typeof getBasePoolsAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBasePoolsAll<
  TData = Awaited<ReturnType<typeof getBasePoolsAll>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBasePoolsAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBasePoolsAll>>,
          TError,
          Awaited<ReturnType<typeof getBasePoolsAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBasePoolsAll<
  TData = Awaited<ReturnType<typeof getBasePoolsAll>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBasePoolsAll>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all base pools
 */

export function useGetBasePoolsAll<
  TData = Awaited<ReturnType<typeof getBasePoolsAll>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBasePoolsAll>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetBasePoolsAllQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
