/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Leekwars Tools API
 * OpenAPI spec version: 4.2.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  AddAIRequest,
  AddAIResponse,
  AnalyzeAIRequest,
  AnalyzeAIResponse,
  EntityAIResponse,
  ListAIResponse,
} from '../leekwarsToolsAPI.schemas';

import { apiClient } from '.././lib/api-client';

/**
 * Adds a new AI file to the system.
 * @summary Add AI
 */
export const postAiAdd = (addAIRequest: AddAIRequest, signal?: AbortSignal) => {
  return apiClient<AddAIResponse>({
    url: `/ai/add`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: addAIRequest,
    signal,
  });
};

export const getPostAiAddMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAiAdd>>,
    TError,
    { data: AddAIRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAiAdd>>,
  TError,
  { data: AddAIRequest },
  TContext
> => {
  const mutationKey = ['postAiAdd'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAiAdd>>,
    { data: AddAIRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postAiAdd(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAiAddMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAiAdd>>
>;
export type PostAiAddMutationBody = AddAIRequest;
export type PostAiAddMutationError = void;

/**
 * @summary Add AI
 */
export const usePostAiAdd = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAiAdd>>,
      TError,
      { data: AddAIRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postAiAdd>>,
  TError,
  { data: AddAIRequest },
  TContext
> => {
  return useMutation(getPostAiAddMutationOptions(options), queryClient);
};
/**
 * Analyzes a specific AI file.
 * @summary Analyze AI
 */
export const postAiAnalyze = (
  analyzeAIRequest: AnalyzeAIRequest,
  signal?: AbortSignal,
) => {
  return apiClient<AnalyzeAIResponse>({
    url: `/ai/analyze`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: analyzeAIRequest,
    signal,
  });
};

export const getPostAiAnalyzeMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAiAnalyze>>,
    TError,
    { data: AnalyzeAIRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAiAnalyze>>,
  TError,
  { data: AnalyzeAIRequest },
  TContext
> => {
  const mutationKey = ['postAiAnalyze'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAiAnalyze>>,
    { data: AnalyzeAIRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postAiAnalyze(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAiAnalyzeMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAiAnalyze>>
>;
export type PostAiAnalyzeMutationBody = AnalyzeAIRequest;
export type PostAiAnalyzeMutationError = void;

/**
 * @summary Analyze AI
 */
export const usePostAiAnalyze = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAiAnalyze>>,
      TError,
      { data: AnalyzeAIRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postAiAnalyze>>,
  TError,
  { data: AnalyzeAIRequest },
  TContext
> => {
  return useMutation(getPostAiAnalyzeMutationOptions(options), queryClient);
};
/**
 * Lists all AIs in the system.
 * @summary List AIs
 */
export const getAiList = (signal?: AbortSignal) => {
  return apiClient<ListAIResponse>({ url: `/ai/list`, method: 'GET', signal });
};

export const getGetAiListQueryKey = () => {
  return [`/ai/list`] as const;
};

export const getGetAiListQueryOptions = <
  TData = Awaited<ReturnType<typeof getAiList>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getAiList>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAiListQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAiList>>> = ({
    signal,
  }) => getAiList(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAiList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAiListQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAiList>>
>;
export type GetAiListQueryError = void;

export function useGetAiList<
  TData = Awaited<ReturnType<typeof getAiList>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAiList>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAiList>>,
          TError,
          Awaited<ReturnType<typeof getAiList>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAiList<
  TData = Awaited<ReturnType<typeof getAiList>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAiList>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAiList>>,
          TError,
          Awaited<ReturnType<typeof getAiList>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAiList<
  TData = Awaited<ReturnType<typeof getAiList>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAiList>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List AIs
 */

export function useGetAiList<
  TData = Awaited<ReturnType<typeof getAiList>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAiList>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAiListQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Gets a specific AI by ID.
 * @summary Get AI
 */
export const getAiId = (id: string, signal?: AbortSignal) => {
  return apiClient<EntityAIResponse>({
    url: `/ai/${id}`,
    method: 'GET',
    signal,
  });
};

export const getGetAiIdQueryKey = (id: string) => {
  return [`/ai/${id}`] as const;
};

export const getGetAiIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getAiId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAiId>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAiIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAiId>>> = ({
    signal,
  }) => getAiId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getAiId>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetAiIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAiId>>
>;
export type GetAiIdQueryError = void;

export function useGetAiId<
  TData = Awaited<ReturnType<typeof getAiId>>,
  TError = void,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAiId>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAiId>>,
          TError,
          Awaited<ReturnType<typeof getAiId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAiId<
  TData = Awaited<ReturnType<typeof getAiId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAiId>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAiId>>,
          TError,
          Awaited<ReturnType<typeof getAiId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAiId<
  TData = Awaited<ReturnType<typeof getAiId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAiId>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get AI
 */

export function useGetAiId<
  TData = Awaited<ReturnType<typeof getAiId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAiId>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAiIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
