/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Leekwars Tools API
 * OpenAPI spec version: 4.2.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  AddTeamRequest,
  AddTeamResponse,
  GetAllTeamsResponse,
} from '../leekwarsToolsAPI.schemas';

import { apiClient } from '.././lib/api-client';

/**
 * Adds a new team to the system.
 * @summary Add a team
 */
export const postTeamsAdd = (
  addTeamRequest: AddTeamRequest,
  signal?: AbortSignal,
) => {
  return apiClient<AddTeamResponse>({
    url: `/teams/add`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: addTeamRequest,
    signal,
  });
};

export const getPostTeamsAddMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postTeamsAdd>>,
    TError,
    { data: AddTeamRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postTeamsAdd>>,
  TError,
  { data: AddTeamRequest },
  TContext
> => {
  const mutationKey = ['postTeamsAdd'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postTeamsAdd>>,
    { data: AddTeamRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postTeamsAdd(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostTeamsAddMutationResult = NonNullable<
  Awaited<ReturnType<typeof postTeamsAdd>>
>;
export type PostTeamsAddMutationBody = AddTeamRequest;
export type PostTeamsAddMutationError = void;

/**
 * @summary Add a team
 */
export const usePostTeamsAdd = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postTeamsAdd>>,
      TError,
      { data: AddTeamRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postTeamsAdd>>,
  TError,
  { data: AddTeamRequest },
  TContext
> => {
  return useMutation(getPostTeamsAddMutationOptions(options), queryClient);
};
/**
 * Returns a list of all teams.
 * @summary Get all teams
 */
export const getTeamsAll = (signal?: AbortSignal) => {
  return apiClient<GetAllTeamsResponse>({
    url: `/teams/all`,
    method: 'GET',
    signal,
  });
};

export const getGetTeamsAllQueryKey = () => {
  return [`/teams/all`] as const;
};

export const getGetTeamsAllQueryOptions = <
  TData = Awaited<ReturnType<typeof getTeamsAll>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getTeamsAll>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTeamsAllQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTeamsAll>>> = ({
    signal,
  }) => getTeamsAll(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getTeamsAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetTeamsAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTeamsAll>>
>;
export type GetTeamsAllQueryError = void;

export function useGetTeamsAll<
  TData = Awaited<ReturnType<typeof getTeamsAll>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTeamsAll>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTeamsAll>>,
          TError,
          Awaited<ReturnType<typeof getTeamsAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTeamsAll<
  TData = Awaited<ReturnType<typeof getTeamsAll>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTeamsAll>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTeamsAll>>,
          TError,
          Awaited<ReturnType<typeof getTeamsAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTeamsAll<
  TData = Awaited<ReturnType<typeof getTeamsAll>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTeamsAll>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all teams
 */

export function useGetTeamsAll<
  TData = Awaited<ReturnType<typeof getTeamsAll>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTeamsAll>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetTeamsAllQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
