/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Leekwars Tools API
 * OpenAPI spec version: 4.2.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  AddLeekToDuelPoolRequest,
  CreateDuelPoolRequest,
  DuelPoolResponse,
  GetDuelPoolsResponse,
  RemoveLeekFromDuelPoolRequest,
} from '../leekwarsToolsAPI.schemas';

import { apiClient } from '.././lib/api-client';

/**
 * Returns a list of all duel pools.
 * @summary Get all duel pools
 */
export const getDuelPoolsAll = (signal?: AbortSignal) => {
  return apiClient<GetDuelPoolsResponse>({
    url: `/duel-pools/all`,
    method: 'GET',
    signal,
  });
};

export const getGetDuelPoolsAllQueryKey = () => {
  return [`/duel-pools/all`] as const;
};

export const getGetDuelPoolsAllQueryOptions = <
  TData = Awaited<ReturnType<typeof getDuelPoolsAll>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getDuelPoolsAll>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDuelPoolsAllQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDuelPoolsAll>>> = ({
    signal,
  }) => getDuelPoolsAll(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDuelPoolsAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDuelPoolsAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDuelPoolsAll>>
>;
export type GetDuelPoolsAllQueryError = void;

export function useGetDuelPoolsAll<
  TData = Awaited<ReturnType<typeof getDuelPoolsAll>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDuelPoolsAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDuelPoolsAll>>,
          TError,
          Awaited<ReturnType<typeof getDuelPoolsAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDuelPoolsAll<
  TData = Awaited<ReturnType<typeof getDuelPoolsAll>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDuelPoolsAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDuelPoolsAll>>,
          TError,
          Awaited<ReturnType<typeof getDuelPoolsAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDuelPoolsAll<
  TData = Awaited<ReturnType<typeof getDuelPoolsAll>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDuelPoolsAll>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all duel pools
 */

export function useGetDuelPoolsAll<
  TData = Awaited<ReturnType<typeof getDuelPoolsAll>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDuelPoolsAll>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetDuelPoolsAllQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Creates a new duel pool in the system.
 * @summary Create a duel pool
 */
export const postDuelPoolsCreate = (
  createDuelPoolRequest: CreateDuelPoolRequest,
  signal?: AbortSignal,
) => {
  return apiClient<DuelPoolResponse>({
    url: `/duel-pools/create`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createDuelPoolRequest,
    signal,
  });
};

export const getPostDuelPoolsCreateMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postDuelPoolsCreate>>,
    TError,
    { data: CreateDuelPoolRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postDuelPoolsCreate>>,
  TError,
  { data: CreateDuelPoolRequest },
  TContext
> => {
  const mutationKey = ['postDuelPoolsCreate'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postDuelPoolsCreate>>,
    { data: CreateDuelPoolRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postDuelPoolsCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostDuelPoolsCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof postDuelPoolsCreate>>
>;
export type PostDuelPoolsCreateMutationBody = CreateDuelPoolRequest;
export type PostDuelPoolsCreateMutationError = void;

/**
 * @summary Create a duel pool
 */
export const usePostDuelPoolsCreate = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postDuelPoolsCreate>>,
      TError,
      { data: CreateDuelPoolRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postDuelPoolsCreate>>,
  TError,
  { data: CreateDuelPoolRequest },
  TContext
> => {
  return useMutation(
    getPostDuelPoolsCreateMutationOptions(options),
    queryClient,
  );
};
/**
 * Returns a duel pool by its ID.
 * @summary Get a duel pool by ID
 */
export const getDuelPoolsId = (id: string, signal?: AbortSignal) => {
  return apiClient<DuelPoolResponse>({
    url: `/duel-pools/${id}`,
    method: 'GET',
    signal,
  });
};

export const getGetDuelPoolsIdQueryKey = (id: string) => {
  return [`/duel-pools/${id}`] as const;
};

export const getGetDuelPoolsIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getDuelPoolsId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDuelPoolsId>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDuelPoolsIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDuelPoolsId>>> = ({
    signal,
  }) => getDuelPoolsId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getDuelPoolsId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDuelPoolsIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDuelPoolsId>>
>;
export type GetDuelPoolsIdQueryError = void;

export function useGetDuelPoolsId<
  TData = Awaited<ReturnType<typeof getDuelPoolsId>>,
  TError = void,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDuelPoolsId>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDuelPoolsId>>,
          TError,
          Awaited<ReturnType<typeof getDuelPoolsId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDuelPoolsId<
  TData = Awaited<ReturnType<typeof getDuelPoolsId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDuelPoolsId>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDuelPoolsId>>,
          TError,
          Awaited<ReturnType<typeof getDuelPoolsId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDuelPoolsId<
  TData = Awaited<ReturnType<typeof getDuelPoolsId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDuelPoolsId>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a duel pool by ID
 */

export function useGetDuelPoolsId<
  TData = Awaited<ReturnType<typeof getDuelPoolsId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDuelPoolsId>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetDuelPoolsIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Adds a leek to an existing duel pool.
 * @summary Add a leek to a duel pool
 */
export const postDuelPoolsIdAddLeek = (
  id: string,
  addLeekToDuelPoolRequest: AddLeekToDuelPoolRequest,
  signal?: AbortSignal,
) => {
  return apiClient<DuelPoolResponse>({
    url: `/duel-pools/${id}/add-leek`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: addLeekToDuelPoolRequest,
    signal,
  });
};

export const getPostDuelPoolsIdAddLeekMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postDuelPoolsIdAddLeek>>,
    TError,
    { id: string; data: AddLeekToDuelPoolRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postDuelPoolsIdAddLeek>>,
  TError,
  { id: string; data: AddLeekToDuelPoolRequest },
  TContext
> => {
  const mutationKey = ['postDuelPoolsIdAddLeek'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postDuelPoolsIdAddLeek>>,
    { id: string; data: AddLeekToDuelPoolRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return postDuelPoolsIdAddLeek(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostDuelPoolsIdAddLeekMutationResult = NonNullable<
  Awaited<ReturnType<typeof postDuelPoolsIdAddLeek>>
>;
export type PostDuelPoolsIdAddLeekMutationBody = AddLeekToDuelPoolRequest;
export type PostDuelPoolsIdAddLeekMutationError = void;

/**
 * @summary Add a leek to a duel pool
 */
export const usePostDuelPoolsIdAddLeek = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postDuelPoolsIdAddLeek>>,
      TError,
      { id: string; data: AddLeekToDuelPoolRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postDuelPoolsIdAddLeek>>,
  TError,
  { id: string; data: AddLeekToDuelPoolRequest },
  TContext
> => {
  return useMutation(
    getPostDuelPoolsIdAddLeekMutationOptions(options),
    queryClient,
  );
};
/**
 * Removes a leek from an existing duel pool.
 * @summary Remove a leek from a duel pool
 */
export const postDuelPoolsIdRemoveLeek = (
  id: string,
  removeLeekFromDuelPoolRequest: RemoveLeekFromDuelPoolRequest,
  signal?: AbortSignal,
) => {
  return apiClient<DuelPoolResponse>({
    url: `/duel-pools/${id}/remove-leek`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: removeLeekFromDuelPoolRequest,
    signal,
  });
};

export const getPostDuelPoolsIdRemoveLeekMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postDuelPoolsIdRemoveLeek>>,
    TError,
    { id: string; data: RemoveLeekFromDuelPoolRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postDuelPoolsIdRemoveLeek>>,
  TError,
  { id: string; data: RemoveLeekFromDuelPoolRequest },
  TContext
> => {
  const mutationKey = ['postDuelPoolsIdRemoveLeek'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postDuelPoolsIdRemoveLeek>>,
    { id: string; data: RemoveLeekFromDuelPoolRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return postDuelPoolsIdRemoveLeek(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostDuelPoolsIdRemoveLeekMutationResult = NonNullable<
  Awaited<ReturnType<typeof postDuelPoolsIdRemoveLeek>>
>;
export type PostDuelPoolsIdRemoveLeekMutationBody =
  RemoveLeekFromDuelPoolRequest;
export type PostDuelPoolsIdRemoveLeekMutationError = void;

/**
 * @summary Remove a leek from a duel pool
 */
export const usePostDuelPoolsIdRemoveLeek = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postDuelPoolsIdRemoveLeek>>,
      TError,
      { id: string; data: RemoveLeekFromDuelPoolRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postDuelPoolsIdRemoveLeek>>,
  TError,
  { id: string; data: RemoveLeekFromDuelPoolRequest },
  TContext
> => {
  return useMutation(
    getPostDuelPoolsIdRemoveLeekMutationOptions(options),
    queryClient,
  );
};
