import { theme } from '../../../../theme';

export const duelPoolCreationStyles = {
  content: {
    overflowY: 'auto' as const,
  },
  title: {
    fontSize: '24px',
    fontWeight: 600,
    marginBottom: theme.spacing.xl,
    color: theme.colors.text.primary,
  },
  form: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: theme.spacing.xl,
    width: '100%',
  },
  section: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: theme.spacing.md,
    padding: theme.spacing.lg,
    backgroundColor: theme.colors.background.secondary,
    borderRadius: theme.borderRadius.md,
    border: `1px solid ${theme.colors.border.primary}`,
  },
  sectionTitle: {
    fontSize: '18px',
    fontWeight: 600,
    color: theme.colors.accent.primary,
    marginBottom: theme.spacing.sm,
  },
  column: {
    display: 'flex',
    gap: theme.spacing.md,
    alignItems: 'flex-start',
    flexWrap: 'wrap' as const,
    flexDirection: 'column' as const,
  },
  inputGroup: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: theme.spacing.xs,
    flex: 1,
    minWidth: '200px',
  },
  label: {
    fontSize: '14px',
    fontWeight: 500,
    color: theme.colors.text.secondary,
  },
  checkboxGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: theme.spacing.sm,
    cursor: 'pointer',
    userSelect: 'none' as const,
  },
  checkboxLabel: {
    fontSize: '14px',
    color: theme.colors.text.primary,
  },
  selectedLeeksContainer: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: theme.spacing.sm,
    marginTop: theme.spacing.sm,
    minHeight: '40px',
    padding: theme.spacing.sm,
    backgroundColor: theme.colors.background.tertiary,
    borderRadius: theme.borderRadius.sm,
    border: `1px dashed ${theme.colors.border.secondary}`,
  },
  removeLeekBtn: {
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '16px',
    height: '16px',
    borderRadius: '50%',
    backgroundColor: 'rgba(0,0,0,0.2)',
    fontSize: '10px',
    transition: 'background-color 0.2s',
  },
  actions: {
    display: 'flex',
    gap: theme.spacing.md,
    marginTop: theme.spacing.md,
    paddingBottom: theme.spacing.xl,
  },
  error: {
    color: theme.colors.accent.error,
    marginTop: theme.spacing.md,
  },
  statsContainer: {
    fontSize: '14px',
    color: theme.colors.text.secondary,
  },
  noLeekSelected: {
    color: '#888',
    fontSize: '12px',
  },
};
